#ifndef MI4IOS6_STAGE69_SHIM_SYS_APPLEAPIOPTS_H
#define MI4IOS6_STAGE69_SHIM_SYS_APPLEAPIOPTS_H

#define __APPLE_API_PRIVATE 1
#define __APPLE_API_STANDARD 1
#define __APPLE_API_STABLE 1
#define __APPLE_API_EVOLVING 1

#endif
