#ifndef MI4IOS6_SHIM_SAN_KASAN_H
#define MI4IOS6_SHIM_SAN_KASAN_H
/*
 * san/kasan.h is generated by the kernel build when KASAN is configured; absent from the tarball.
 * KASAN off is the released configuration and exercises less code, not more - the same reasoning as
 * MACH_ASSERT 0 and CONFIG_DTRACE 0.
 */
#define KASAN 0
#define kasan_poison(x, y) do { } while (0)
#define kasan_unpoison(x, y) do { } while (0)
#define kasan_require_heap(x) do { } while (0)
#endif
