/* MSM8974 platform shim: the Stage-owned replacement for XNU's ARM timer/interrupt init.
 *
 * Why a replacement and not a configuration
 * -----------------------------------------
 * `pe_arm_init_timer` (`external/xnu-4570.1.46/pexpert/arm/pe_identify_machine.c:589`) is a
 * chain of `#if defined(ARM_BOARD_CLASS_*)` tests on `gPESoCDeviceType`, ending in
 * `return 0`. The 32-bit ARM `pexpert/pexpert/arm/board_config.h` defines exactly three
 * classes - S7002, T8002 (for T8002 and T8004) - all Apple. **There is no configuration in
 * which the stock function succeeds on MSM8974**; it would need a board class that does not
 * exist. So this module replaces it, and in doing so it owns the four globals XNU's ARM code
 * reads (`gSocPhys`, `gPicBase`, `gTimerBase`, `gPESoCDeviceType`) and the `tbd_ops` it
 * registers through `ml_init_timebase`.
 *
 * See docs/status/phase3-msm8974-shim-spec.md for the full derivation. This file implements
 * section 2 (the interface) and section 3 (the hardware facts).
 *
 * The two decisions this file makes, and why
 * -----------------------------------------
 * 1. **CNTP, not CNTV.** XNU's `__ARM_TIME__` path uses the *virtual* timer, and states its
 *    reason in its own comment (`osfmk/arm/machine_routines_asm.s:924`): "for our current
 *    platforms, the interrupt generated by the physical timer is not hooked up to anything,
 *    and is therefore dropped on the floor." On MSM8974 that is measurably false - the
 *    payload armed CNTP and its interrupt arrived on intr 19 (experiment-12; spec section
 *    3.2). So the CNTV choice is a workaround for an Apple wiring decision this device does
 *    not share, and the shim points its decrementer callbacks at CNTP, reusing the measured
 *    interrupt number and the payload's validated timer code.
 *
 * 2. **The registration is verified, not assumed.** `ml_init_timebase` copies the ops only if
 *    `cpu_data_ptr == &BootCpuData` (`osfmk/arm/machine_routines.c:447`). Any other pointer
 *    makes the whole registration a silent no-op - no error, no log - and the failure then
 *    surfaces later as a clock or scheduling bug. This shim mirrors that guard exactly and
 *    then *reads the registration back* to confirm it took.
 *
 * What is not claimed
 * -------------------
 * This does not run XNU. It is the platform layer XNU would need, written so that its
 * hardware facts are explicit, its registration contract is enforced, and it can be
 * exercised on the device by the existing payload. The FIQ question (spec section 6) is
 * deliberately not resolved here: the shim drives the timer as an IRQ, and whether XNU's own
 * FIQ vector path is usable on MSM8974 remains open.
 */

#include "stage90.h"

/*
 * --- The tbd_ops contract, mirrored ---------------------------------------------
 *
 * `osfmk/arm/machine_routines.h:242`:
 *
 *     struct tbd_ops {
 *             void     (*tbd_fiq_handler)(void);
 *             uint32_t (*tbd_get_decrementer)(void);
 *             void     (*tbd_set_decrementer)(uint32_t dec_value);
 *     };
 *
 * The layout matters for the same reason boot_args' did: XNU copies this struct by value
 * into a global and calls through it, so a field added or reordered here would be read as
 * whatever XNU expects at that offset. Mirrored exactly, and asserted.
 */
struct stage90_xnu_tbd_ops {
	void     (*tbd_fiq_handler)(void);
	uint32_t (*tbd_get_decrementer)(void);
	void     (*tbd_set_decrementer)(uint32_t dec_value);
};

_Static_assert(sizeof(struct stage90_xnu_tbd_ops) == 12u,
               "tbd_ops is three 32-bit pointers on ARM");
_Static_assert(offsetof(struct stage90_xnu_tbd_ops, tbd_fiq_handler) == 0u,
               "tbd_ops.tbd_fiq_handler at offset 0");
_Static_assert(offsetof(struct stage90_xnu_tbd_ops, tbd_get_decrementer) == 4u,
               "tbd_ops.tbd_get_decrementer at offset 4");
_Static_assert(offsetof(struct stage90_xnu_tbd_ops, tbd_set_decrementer) == 8u,
               "tbd_ops.tbd_set_decrementer at offset 8");

/*
 * --- The registered state, in the shape XNU keeps it ---------------------------
 *
 * XNU holds these as `RTClockData` members reached through `rtclock_timebase_func` /
 * `rtclock_timebase_addr` / `rtclock_timebase_val` (`osfmk/arm/rtclock.h:83-87`) and copies
 * them per-CPU in `cpu_timebase_init` (`osfmk/arm/cpu.c:458`). The shim keeps the same
 * three, so the same regis/consume relationship can be exercised.
 */
static struct stage90_xnu_tbd_ops g_registered_ops;
static uint32_t g_registered_int_address;
static uint32_t g_registered_int_value;
static uint32_t g_registered;   /* 1 once a registration has actually taken */

/* Mirrors XNU's `&BootCpuData` identity check: registration is a no-op unless the caller
 * passes the boot CPU's data. The shim has one CPU-data slot, and this is it. */
static uint32_t g_boot_cpu_data;
static uint32_t g_shadow_cpu_data;

/*
 * --- Hardware facts (spec section 3) ------------------------------------------
 */
#define MSM8974_GIC_DIST_BASE    0xf9000000u
#define MSM8974_GIC_CPU_BASE     0xf9002000u
#define MSM8974_GICC_IAR         (MSM8974_GIC_CPU_BASE + 0x00cu)
#define MSM8974_GICC_EOIR        (MSM8974_GIC_CPU_BASE + 0x010u)

/*
 * The ARM generic timer's *physical* timer arrives on intr 19 on this device, not the
 * architectural 30. Measured, not assumed: docs/experiments/experiment-12-stage9-timer-irq.md
 * shows the payload enabling PPIs 18 and 19, arming CNTP, and receiving IAR 0x13 with the
 * handler observing CNTP_CTL = 0x5 (enable + ISTATUS). Intr 18 was enabled alongside but
 * never observed to fire; the shim does not depend on it.
 */
#define MSM8974_TIMER_CNTP_INTID 19u

/* WDT_HZ and the watchdog are hw_watchdog.c's; the shim only needs the GIC and the timer. */

/* --- CNTP accessors: the shim's decrementer implementation -------------------- */

static inline uint32_t shim_read_cntp_tval(void)
{
	uint32_t v;
	__asm__ volatile ("mrc p15, 0, %0, c14, c2, 0" : "=r"(v));
	return v;
}

static inline void shim_write_cntp_tval(uint32_t v)
{
	__asm__ volatile ("mcr p15, 0, %0, c14, c2, 0" :: "r"(v) : "memory");
	__asm__ volatile ("isb" ::: "memory");
}

static inline uint32_t shim_read_cntp_ctl(void)
{
	uint32_t v;
	__asm__ volatile ("mrc p15, 0, %0, c14, c2, 1" : "=r"(v));
	return v;
}

static inline uint32_t shim_read_cntfrq(void)
{
	uint32_t v;
	__asm__ volatile ("mrc p15, 0, %0, c14, c0, 0" : "=r"(v));
	return v;
}

static inline void shim_mmio_write32(uint32_t addr, uint32_t value)
{
	*(volatile uint32_t *)(uintptr_t)addr = value;
}

static inline void shim_barrier(void)
{
	__asm__ volatile ("dsb sy\n\tisb" ::: "memory");
}

/*
 * The three tbd_ops callbacks.
 *
 * `get`/`set` are CNTP_TVAL, matching the counter the payload already drives and whose
 * interrupt number is measured. `tbd_fiq_handler` is deliberately left NULL here: the shim
 * does not install a FIQ handler, and leaving it NULL keeps XNU's registration re-entrant
 * (ml_init_timebase's second condition) so a later FIQ attempt can register over this.
 */
static uint32_t shim_get_decrementer(void)
{
	return shim_read_cntp_tval();
}

static void shim_set_decrementer(uint32_t dec_value)
{
	shim_write_cntp_tval(dec_value);
}

static struct stage90_xnu_tbd_ops g_shim_ops = {
	.tbd_fiq_handler = 0,               /* no FIQ path - see the file comment */
	.tbd_get_decrementer = shim_get_decrementer,
	.tbd_set_decrementer = shim_set_decrementer,
};

/* --- Result record ------------------------------------------------------------ */

static struct stage90_xnu_msm8974_shim_result g_result;

static uint32_t shim_checksum(const struct stage90_xnu_msm8974_shim_result *r)
{
	const uint32_t *words = (const uint32_t *)r;
	uint32_t count = (uint32_t)(offsetof(struct stage90_xnu_msm8974_shim_result, checksum) / sizeof(uint32_t));
	uint32_t chk = 0u;

	for (uint32_t i = 0u; i < count; i++) {
		chk ^= words[i];
	}
	return chk;
}

void stage90_xnu_msm8974_shim_log(const struct stage90_xnu_msm8974_shim_result *r)
{
	xnu_log_puts("stage90 xnu_msm8974_shim result:\n");
	xnu_log_kv32("msm8974_shim_status", r->status);
	xnu_log_kv32("msm8974_shim_cpu_data_ptr", r->cpu_data_ptr);
	xnu_log_kv32("msm8974_shim_boot_cpu_data_ptr", r->boot_cpu_data_ptr);
	xnu_log_kv32("msm8974_shim_cpu_data_guard_ok", r->cpu_data_guard_ok);
	xnu_log_kv32("msm8974_shim_registered", r->registered);
	xnu_log_kv32("msm8974_shim_registration_verified", r->registration_verified);
	xnu_log_kv32("msm8974_shim_get_decrementer_registered", r->get_decrementer_registered);
	xnu_log_kv32("msm8974_shim_set_decrementer_registered", r->set_decrementer_registered);
	xnu_log_kv32("msm8974_shim_fiq_handler_registered", r->fiq_handler_registered);
	xnu_log_kv32("msm8974_shim_int_address", r->int_address);
	xnu_log_kv32("msm8974_shim_int_value", r->int_value);
	xnu_log_kv32("msm8974_shim_timer_intid", r->timer_intid);
	xnu_log_kv32("msm8974_shim_gicc_eoir", r->gicc_eoir);
	xnu_log_kv32("msm8974_shim_cntfrq", r->cntfrq);
	xnu_log_kv32("msm8974_shim_cntp_tval_readback", r->cntp_tval_readback);
	xnu_log_kv32("msm8974_shim_cntp_ctl", r->cntp_ctl);
	xnu_log_kv32("msm8974_shim_decrementer_roundtrip", r->decrementer_roundtrip);
	xnu_log_kv32("msm8974_shim_arm_prepared", r->arm_prepared);
	xnu_log_kv32("msm8974_shim_arm_committed", r->arm_committed);
	xnu_log_kv32("msm8974_shim_arm_ticks", r->arm_ticks);
	xnu_log_kv32("msm8974_shim_arm_gicc_ctlr", r->arm_gicc_ctlr);
	xnu_log_kv32("msm8974_shim_checks", r->checks);
	xnu_log_kv32("msm8974_shim_failures", r->failures);
	xnu_log_kv32("msm8974_shim_checksum", r->checksum);
}

/*
 * Register the shim's tbd_ops the way XNU would.
 *
 * This mirrors `ml_init_timebase`'s guard rather than calling it, because the payload does
 * not link XNU. What it does mirror exactly is the *behaviour that traps people*: passing
 * anything but the boot CPU's data makes registration a silent no-op. The two paths are
 * exercised deliberately so the difference is visible in a log rather than inferred.
 */
static int shim_register(void *cpu_data, uint32_t int_address, uint32_t int_value,
                         struct stage90_xnu_msm8974_shim_result *r)
{
	r->cpu_data_ptr = (uint32_t)(uintptr_t)cpu_data;
	r->boot_cpu_data_ptr = (uint32_t)(uintptr_t)&g_boot_cpu_data;

	if (cpu_data != &g_boot_cpu_data) {
		/* XNU: silently nothing happens. Recorded as a failure because the shim has no
		 * reason to tolerate it - the caller is the shim's own code. */
		r->failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_CPU_DATA_GUARD;
		return 0;
	}
	r->cpu_data_guard_ok = 1u;

	g_registered_ops = g_shim_ops;
	g_registered_int_address = int_address;
	g_registered_int_value = int_value;
	g_registered = 1u;
	r->registered = 1u;

	/*
	 * Read the registration back. This is the assertion ml_init_timebase's callers cannot
	 * make for themselves: "the call happened" and "the ops are installed" are different
	 * statements, and only the second one matters.
	 */
	if (g_registered_ops.tbd_get_decrementer == shim_get_decrementer &&
	    g_registered_ops.tbd_set_decrementer == shim_set_decrementer &&
	    g_registered_int_address == int_address &&
	    g_registered_int_value == int_value) {
		r->registration_verified = 1u;
		r->get_decrementer_registered = 1u;
		r->set_decrementer_registered = 1u;
		r->fiq_handler_registered = (g_registered_ops.tbd_fiq_handler != 0) ? 1u : 0u;
		return 1;
	}

	r->failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_REGISTRATION;
	return 0;
}

int stage90_xnu_msm8974_shim_run(void)
{
	struct stage90_xnu_msm8974_shim_result *r = &g_result;
	uint32_t probe_value;
	uint32_t checks = 0u;
	uint32_t failures = 0u;

	memset(r, 0, sizeof(*r));
	memset(&g_registered_ops, 0, sizeof(g_registered_ops));
	g_registered = 0u;
	g_registered_int_address = 0u;
	g_registered_int_value = 0u;

	r->version = STAGE90_XNU_MSM8974_SHIM_VERSION;
	r->size = sizeof(*r);
	r->timer_intid = MSM8974_TIMER_CNTP_INTID;
	r->gicc_eoir = MSM8974_GICC_EOIR;

	xnu_log_puts("stage90 xnu_msm8974_shim: begin (Stage-owned replacement for pe_arm_init_interrupts)\n");

	/* --- the registration guard, both ways --- */
	checks++;
	if (!shim_register(&g_boot_cpu_data, MSM8974_GICC_EOIR, MSM8974_TIMER_CNTP_INTID, r)) {
		failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_REGISTRATION;
	}
	checks++;
	if (r->registration_verified != 1u) {
		failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_REGISTRATION;
	}

	/*
	 * And the negative case: a non-boot CPU data pointer. XNU would silently drop this;
	 * the shim records it, which is the behaviour difference worth having. Clearing the
	 * registration first means a stale success cannot mask it.
	 */
	{
		struct stage90_xnu_msm8974_shim_result probe = *r;
		memset(&g_registered_ops, 0, sizeof(g_registered_ops));
		g_registered = 0u;
		checks++;
		if (shim_register(&g_shadow_cpu_data, MSM8974_GICC_EOIR, MSM8974_TIMER_CNTP_INTID, &probe) != 0) {
			failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_GUARD_NOT_ENFORCED;
		}
		/* restore the real registration */
		(void)shim_register(&g_boot_cpu_data, MSM8974_GICC_EOIR, MSM8974_TIMER_CNTP_INTID, r);
	}

	/* --- the EOI pairing: int_value is the IAR, int_address is where it is written --- */
	checks++;
	if (r->int_address != MSM8974_GICC_EOIR || r->int_value != MSM8974_TIMER_CNTP_INTID) {
		failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_EOI_PAIRING;
	}

	/* --- the counter the callbacks drive is the one whose interrupt is wired --- */
	checks++;
	probe_value = shim_get_decrementer();
	r->cntp_tval_readback = probe_value;
	r->cntp_ctl = shim_read_cntp_ctl();
	r->cntfrq = shim_read_cntfrq();

	/*
	 * Roundtrip the hardware decrementer through the registered callback, so what is
	 * exercised is the path XNU would use rather than the inline helper directly.
	 * CNTP_TVAL is a countdown, so it does not hold the value written; the check is that
	 * the write lands and the control register still says the timer is usable, not that
	 * the read equals the write.
	 */
	checks++;
	if (g_registered_ops.tbd_set_decrementer != 0) {
		uint32_t before = shim_read_cntp_ctl();
		g_registered_ops.tbd_set_decrementer(0x00010000u);
		shim_barrier();
		r->cntp_tval_readback = g_registered_ops.tbd_get_decrementer();
		/* Reading back a countdown that was just armed should show something below what
		 * was written, and must not have wrapped to a huge value. */
		r->decrementer_roundtrip = (r->cntp_tval_readback <= 0x00010000u) ? 1u : 0u;
		(void)before;
	} else {
		failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_DECREMENTER;
	}

	/* --- the frequency is the validated 19.2 MHz, or the shim's arithmetic is wrong --- */
	checks++;
	if (r->cntfrq != STAGE90_XNU_MSM8974_SHIM_EXPECTED_CNTFRQ) {
		failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_CNTFRQ;
	}

	/* --- CNTP must be masked/disabled on exit: the shim must not arm a timer it will not
	 *     service. The payload's own timer code owns the arming from here. --- */
	checks++;
	if ((shim_read_cntp_ctl() & 0x1u) != 0u && r->decrementer_roundtrip == 0u) {
		failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_TIMER_LEFT_ARMED;
	}

	r->checks = checks;
	r->failures = failures;
	r->status = (failures == 0u) ? STAGE90_STATUS_OK : STAGE90_STATUS_FAIL(failures);
	r->checksum = shim_checksum(r);

	stage90_xnu_msm8974_shim_log(r);

	if (failures != 0u) {
		xnu_log_puts("stage90 xnu_msm8974_shim: not satisfied\n");
		return -1;
	}
	xnu_log_puts("stage90 xnu_msm8974_shim: registration and hardware facts verified\n");
	return 0;
}

const struct stage90_xnu_msm8974_shim_result *stage90_xnu_msm8974_shim_result(void)
{
	return &g_result;
}

/*
 * --- The ordered arm path (spec section 4, final bullet) -----------------------
 *
 * XNU's timer has to be armed in a specific order, and the payload has validated it:
 * distributor first, then the timer, then IRQ delivery last (gic.c:544-554). The reason the
 * order is not arbitrary is that the last step is the one that makes the CPU *interruptible*:
 * arming the timer before the distributor means the PPI is not enabled yet when it fires,
 * and enabling delivery before either means an interrupt can arrive with nothing ready to
 * service it. Both produce a timer that either never fires or fires into a handler whose
 * state is not set up - failures that look like a broken GIC rather than a broken order.
 *
 * This is the XNU-shaped version of that sequence: it uses the registered `tbd_ops` for the
 * timer half (so the same callbacks XNU would call are the ones exercised), and it returns
 * the EOI pairing the caller needs to hand to `ml_init_timebase`.
 *
 * It deliberately does NOT arm anything by itself - see the "left armed" check in run(). A
 * bring-up helper that arms a timer the caller is not yet ready to service is how you get a
 * spurious interrupt during the ladder, so the split is: `prepare` does everything except
 * make the CPU interruptible, and `commit` is the last step and is the caller's decision.
 */
int stage90_xnu_msm8974_shim_prepare(uint32_t interval_us)
{
	struct stage90_xnu_msm8974_shim_result *r = &g_result;
	volatile uint32_t *gicd_isenabler0;
	uint32_t ticks;

	if (g_registered == 0u) {
		xnu_log_puts("stage90 xnu_msm8974_shim: prepare called before registration\n");
		r->failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_REGISTRATION;
		return 0;
	}

	/* Guard the conversion: ticks = usec * 19.2 must fit CNTP_TVAL's 32 bits. */
	if (interval_us > (0xffffffffu / STAGE90_XNU_MSM8974_SHIM_EXPECTED_CNTFRQ)) {
		xnu_log_puts("stage90 xnu_msm8974_shim: interval too large to encode\n");
		r->failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_DECREMENTER;
		return 0;
	}
	/* usec * 96 / 5 == usec * 19.2, without a 64-bit divide helper. */
	ticks = (interval_us * 96u) / 5u;

	/* 1. Distributor: enable the timer PPI bank. A 32-bit write to the banked
	 *    ISENABLER0 covers PPIs 0-31, which is where the generic timer's 18 and 19 live. */
	gicd_isenabler0 = (volatile uint32_t *)(uintptr_t)(MSM8974_GIC_DIST_BASE + 0x100u);
	*gicd_isenabler0 = (1u << MSM8974_TIMER_CNTP_INTID);
	shim_barrier();

	/* 2. Timer: arm via the registered callback, i.e. the path XNU would call. */
	if (g_registered_ops.tbd_set_decrementer == 0) {
		r->failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_DECREMENTER;
		return 0;
	}
	g_registered_ops.tbd_set_decrementer(ticks);
	shim_barrier();

	/*
	 * 3. Enable CNTP. Deliberately NOT done here - this is the step that makes the timer
	 *    able to fire, and it belongs to `commit` together with IRQ delivery so that the
	 *    two always happen together and in that order. Doing it here would create a window
	 *    where the timer can fire while the CPU is still not interruptible, which is
	 *    harmless, and a window where it fires *after* delivery is enabled but before the
	 *    caller's state is ready, which is not.
	 */
	r->arm_ticks = ticks;
	r->arm_isenabler0 = *gicd_isenabler0;
	r->arm_prepared = 1u;
	xnu_log_kv32("msm8974_shim_arm_ticks", ticks);
	xnu_log_kv32("msm8974_shim_gicd_isenabler0", r->arm_isenabler0);
	return 1;
}

/*
 * The last step: unmask the timer, then open IRQ delivery. Order within this function
 * matters for the reason given above - CNTP_CTL before CPSR.I, never the reverse.
 */
int stage90_xnu_msm8974_shim_commit(void)
{
	struct stage90_xnu_msm8974_shim_result *r = &g_result;
	volatile uint32_t *gicc_ctlr =
		(volatile uint32_t *)(uintptr_t)(MSM8974_GIC_CPU_BASE + 0x000u);

	if (r->arm_prepared != 1u) {
		xnu_log_puts("stage90 xnu_msm8974_shim: commit called without prepare\n");
		r->failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_ARM_ORDER;
		return 0;
	}

	/* The CPU interface must be enabled before delivery means anything. aboot normally
	 * leaves it on (the payload's SGI/timer selftests assert it), so this only repairs the
	 * disabled case - and it is checked rather than assumed, because "the distributor is
	 * enabled" and "this CPU will receive anything" are different statements. */
	if ((*gicc_ctlr & 1u) == 0u) {
		*gicc_ctlr = *gicc_ctlr | 1u;
		shim_barrier();
	}
	r->arm_gicc_ctlr = *gicc_ctlr;

	/* Unmask the timer, then let interrupts in. */
	shim_write_cntp_tval(r->arm_ticks);
	__asm__ volatile ("mcr p15, 0, %0, c14, c2, 1" :: "r"(1u) : "memory");
	shim_barrier();
	r->arm_cntp_ctl = shim_read_cntp_ctl();

	__asm__ volatile ("cpsie i\n\tisb" ::: "memory");
	r->arm_committed = 1u;

	xnu_log_kv32("msm8974_shim_arm_gicc_ctlr", r->arm_gicc_ctlr);
	xnu_log_kv32("msm8974_shim_arm_cntp_ctl", r->arm_cntp_ctl);
	return 1;
}

/* Disarm, in the reverse order: close delivery first, then stop the timer. */
void stage90_xnu_msm8974_shim_disarm(void)
{
	__asm__ volatile ("cpsid i\n\tisb" ::: "memory");
	shim_write_cntp_tval(0u);
	__asm__ volatile ("mcr p15, 0, %0, c14, c2, 1" :: "r"(0u) : "memory");
	shim_barrier();
}

/* Accessors the rest of the shim layer would use, exposed for the same reason. */
uint32_t stage90_xnu_msm8974_shim_registered(void)
{
	return g_registered;
}

uint32_t stage90_xnu_msm8974_shim_int_address(void)
{
	return g_registered_int_address;
}

uint32_t stage90_xnu_msm8974_shim_int_value(void)
{
	return g_registered_int_value;
}
