/*
 * Enter XNU. For real.
 *
 * Every other switch in this project runs XNU *code* - five pexpert objects, one subsystem at a
 * time - inside the payload's own context, on the payload's own page tables, with the payload's
 * own scheduler-less runtime underneath. This one does something categorically different: it
 * copies a linked image containing XNU's own `_start` to a base of its own, hands it a
 * `boot_args`, and jumps to it. From that instruction onward the page tables, the vectors, the
 * caches and the MMU state are XNU's, not ours, and this payload never runs again.
 *
 * What makes that possible at all is experiment-103's finding: `_start` does not want a page
 * table from us, it *builds* one. It needs a `boot_args` describing where it was linked and a
 * writable, aligned `topOfKernelData` with room - and then it does the rest itself. So the
 * payload's job here is small and entirely mechanical:
 *
 *   1. map the window it is about to use, because the payload's identity table covers only the
 *      first two megabytes (mmu.c does that step, gated on this switch);
 *   2. copy the entry image in and zero its BSS;
 *   3. publish both, because with caches on the payload's writes may still be dirty, and XNU will
 *      read them through an MMU it has just re-pointed at the same physical memory;
 *   4. build the `boot_args`  **inside** that window, so it is readable on both sides of the page
 *      table switch;
 *   5. jump.
 *
 * The base and the `boot_args` together make every `LOAD_PHYS_ADDR` conversion inside `_start` an
 * identity - `physBase == virtBase` - which is what lets the entry image's own epilogue turn the
 * MMU off and keep executing from the same addresses.
 *
 * What you should expect to see in `/proc/last_kmsg` if it works
 * ------------------------------------------------------------
 *   ...                                                     <- everything the payload logged
 *   MI4IOS6_STAGE90_XNU xnu_entry: jumping to XNU's _start at 0x00200074
 *   MI4IOS6_STAGE90_XNU real XNU entry: _start ran to completion and branched to arm_init
 *   ...                                                     <- then platform_reboot
 *
 * The second line is written by code in the entry image, with the MMU off, after `_start` has
 * done everything a kernel entry point does. It is the whole result.
 *
 * What you should expect if it fails
 * ----------------------------------
 * A line naming the vector instead - `exception: prefetch abort`, `exception: data abort` and so
 * on - because `_start` installs exception vectors in the entry image before it switches tables,
 * and those stubs report which one fired. A hang with neither line is also possible: in that case
 * the payload never got as far as the jump, and the log ends at the last line it wrote. Both nets
 * are armed, so a hang costs a watchdog reset rather than a power press.
 *
 * What this deliberately does NOT do
 * ----------------------------------
 * It does not arm the software dead-man across the jump. The dead-man needs the payload's GIC
 * and vector state, and both are gone the moment `_start` switches tables; leaving it armed would
 * be a claim that cannot be honoured. The hardware watchdog is what covers this window, and it
 * covers it for the reason it exists - it needs nothing from the CPU's configuration at all.
 */

#include "stage90.h"
#include "xnu_arm_entry.h"

/*
 * The entry image, generated by xnu_arm_boot/build_entry.sh. It carries XNU's `_start` and the
 * symbols `_start` needs; see xnu_arm_boot/entry_stubs.c for what those are and why they can
 * report their own failure.
 */
extern const uint8_t stage90_xnu_entry_blob[];
extern const uint32_t stage90_xnu_entry_blob_size;

/*
 * Where everything above the image goes. All three offsets come from the generated
 * `xnu_arm_entry.h`, which build_entry.sh writes after it links the image, and they were constants
 * here until experiment 175 - which is one experiment after the second time two copies of one of
 * them disagreed. Each is checked at build time against the one before it, so an image that grows
 * moves them and nothing here has to be edited.
 *
 * The boot_args copy is the first page above the image; `topOfKernelData` is where `_start` builds
 * its own page tables; the device tree is 2 MB above that, so it clears the 40 KB of tables
 * `start.s` writes by more than any tree this project builds will need. The tree is 0x7294 bytes
 * today and its buffer is sized for four times that.
 */
#define ENTRY_ARGS_OFFSET   STAGE90_XNU_ENTRY_ARGS_OFFSET
#define ENTRY_ARGS_PA       (STAGE90_XNU_ENTRY_BASE + ENTRY_ARGS_OFFSET)
#define ENTRY_DT_OFFSET     STAGE90_XNU_ENTRY_DT_OFFSET
#define ENTRY_DT_PA         (STAGE90_XNU_ENTRY_BASE + ENTRY_DT_OFFSET)
#define ENTRY_DT_MAX        STAGE90_XNU_ENTRY_DT_MAX

static struct stage90_xnu_entry_result g_result;

/*
 * The jump itself. r0 is already the argument (AAPCS), so this is `bx r1` with a guard behind it
 * so a mistake cannot fall through into whatever the compiler put next.
 *
 * `naked` because a compiler-generated prologue would touch the stack, and after the jump the
 * stack is XNU's; the arguments are taken in registers. It does not return, ever.
 */
__attribute__((naked, noreturn)) static void xnu_entry_jump(uint32_t boot_args_pa, uint32_t entry)
{
    /* The two parameters are AAPCS r0 and r1; naming them documents the call and the linker
     * needs no more, but the body cannot refer to them (naked), hence the casts. */
    (void)boot_args_pa;
    (void)entry;
    __asm__ volatile (
        "bx     r1\n\t"
        "1:     b   1b\n\t"
    );
}

static void xnu_entry_copy_device_tree(const struct boot_args *src)
{
    void *dest = (void *)(uintptr_t)ENTRY_DT_PA;

    if (src->deviceTreeP == NULL || src->deviceTreeLength == 0u ||
        src->deviceTreeLength > ENTRY_DT_MAX) {
        xnu_log_kv32("xnu_entry_device_tree_len", src->deviceTreeLength);
        xnu_log_puts("xnu_entry: refusing to copy a device tree of that size\n");
        return;
    }

    memcpy(dest, src->deviceTreeP, src->deviceTreeLength);
    /* Same reasoning as the image: XNU reads this through page tables it writes itself. */
    cache_clean_dcache_range(ENTRY_DT_PA, src->deviceTreeLength);

    xnu_log_kv32("xnu_entry_device_tree_pa", ENTRY_DT_PA);
    xnu_log_kv32("xnu_entry_device_tree_len", src->deviceTreeLength);
}

static void xnu_entry_build_args(const struct boot_args *src)
{
    /*
     * Written at the physical address directly - the window is identity-mapped, so the pointer and
     * the PA are the same number, and saying it as a PA is what makes that obvious rather than
     * incidental.
     */
    struct boot_args *a = (struct boot_args *)(uintptr_t)ENTRY_ARGS_PA;

    memset(a, 0, sizeof(*a));
    a->Revision = BOOT_ARGS_REVISION;
    a->Version = BOOT_ARGS_VERSION;
    /*
     * physBase == virtBase is the whole trick. `_start` computes `addr - virtBase + physBase` for
     * every symbol it uses, so equal values make that the identity and let the entry image keep
     * running after it maps itself and after it later unmaps itself.
     */
    a->virtBase = STAGE90_XNU_ENTRY_BASE;
    a->physBase = STAGE90_XNU_ENTRY_BASE;
    /*
     * The whole window, so `_start`'s section loop covers the image and the tables. It is 8 MB as
     * of experiment 175 rather than the 2 MB it was through 168-174, because the layout above the
     * image is now derived from the image: the tree sits at +4 MB and takes memSize at least that
     * far. `_start` walks memSize in section-sized steps setting up the page tables for whatever
     * it finds, so a value larger than what is populated only costs that walk.
     */
    a->memSize = STAGE90_XNU_ENTRY_SIZE;
    /*
     * Above the image and its BSS, which is the invariant build_entry.sh checks against this same
     * macro: `_start` writes 40 KB of table entries starting here, so anything the image owns must
     * end below it. It sits one page above the boot_args, which is what keeps those tables off the
     * boot_args page. The value comes from the generated `xnu_arm_entry.h` so that the build and
     * this boot_args cannot disagree about it.
     */
    a->topOfKernelData = STAGE90_XNU_ENTRY_BASE + STAGE90_XNU_TOP_OF_KERNEL_DATA_OFFSET;
    a->machineType = 0x00009074u;
    /* The tree, copied in. `_start` does not read it; `arm_init` and everything after does. */
    a->deviceTreeP = (void *)(uintptr_t)ENTRY_DT_PA;
    a->deviceTreeLength = (src->deviceTreeLength <= ENTRY_DT_MAX) ? src->deviceTreeLength : 0u;
    a->bootFlags = 0u;
    a->memSizeActual = STAGE90_XNU_ENTRY_SIZE;
    /* The command line goes with it, so XNU's parser has one to read. */
    memcpy(a->CommandLine, src->CommandLine, sizeof(a->CommandLine));
    a->CommandLine[sizeof(a->CommandLine) - 1u] = '\0';

    xnu_log_kv32("xnu_entry_args_pa", ENTRY_ARGS_PA);
    xnu_log_kv32("xnu_entry_args_virtBase", a->virtBase);
    xnu_log_kv32("xnu_entry_args_physBase", a->physBase);
    xnu_log_kv32("xnu_entry_args_memSize", a->memSize);
    xnu_log_kv32("xnu_entry_args_topOfKernelData", a->topOfKernelData);
}

int stage90_xnu_entry_run(const struct boot_args *args)
{
    struct stage90_xnu_entry_result *r = &g_result;
    uint8_t *dest = (uint8_t *)(uintptr_t)STAGE90_XNU_ENTRY_BASE;

    memset(r, 0, sizeof(*r));
    r->version = STAGE90_XNU_ENTRY_VERSION;
    r->size = sizeof(*r);
    r->entry_base = STAGE90_XNU_ENTRY_BASE;
    r->entry_va = STAGE90_XNU_ENTRY_ENTRY;
    r->image_bytes = stage90_xnu_entry_blob_size;
    r->bss_start = STAGE90_XNU_ENTRY_BSS_START;
    r->bss_end = STAGE90_XNU_ENTRY_BSS_END;
    r->args_pa = ENTRY_ARGS_PA;
    r->top_of_kernel_data = STAGE90_XNU_ENTRY_BASE + STAGE90_XNU_TOP_OF_KERNEL_DATA_OFFSET;

    xnu_log_puts("stage90 xnu_entry: entering XNU - this is the last thing the payload does\n");

    /*
     * Refuse rather than guess if the image does not fit where the linker script and the
     * boot_args both say it is. A mismatch here would surface as `_start` executing whatever
     * happened to be at the base, which is the least debuggable failure available.
     */
    if (stage90_xnu_entry_blob_size == 0u ||
        STAGE90_XNU_ENTRY_ENTRY < STAGE90_XNU_ENTRY_BASE ||
        STAGE90_XNU_ENTRY_ENTRY >= STAGE90_XNU_ENTRY_BASE + STAGE90_XNU_ENTRY_SIZE ||
        STAGE90_XNU_ENTRY_BSS_END >
        STAGE90_XNU_ENTRY_BASE + STAGE90_XNU_TOP_OF_KERNEL_DATA_OFFSET) {
        xnu_log_puts("xnu_entry: the linked image does not match the window it is copied to\n");
        r->status = STAGE90_STATUS_BASE;
        r->checksum = stage90_xnu_entry_checksum(r);
        stage90_xnu_entry_log(r);
        return -1;
    }

    /* 1. the image */
    memcpy(dest, stage90_xnu_entry_blob, stage90_xnu_entry_blob_size);
    xnu_log_kv32("xnu_entry_copied_to", STAGE90_XNU_ENTRY_BASE);
    xnu_log_kv32("xnu_entry_copied_bytes", stage90_xnu_entry_blob_size);

    /* 2. its BSS, which objcopy does not carry in a binary */
    memset((void *)(uintptr_t)STAGE90_XNU_ENTRY_BSS_START, 0,
           STAGE90_XNU_ENTRY_BSS_END - STAGE90_XNU_ENTRY_BSS_START);
    xnu_log_kv32("xnu_entry_bss_bytes", STAGE90_XNU_ENTRY_BSS_END - STAGE90_XNU_ENTRY_BSS_START);

    /* 3. the device tree and the boot_args, both inside the window
     *
     * The payload's own boot_args is the source for the tree and the command line - it is what
     * this boot was actually started with - and the copy in the window is what XNU is handed.
     */
    xnu_entry_copy_device_tree(args);
    xnu_entry_build_args(args);

    /*
     * 4. publish both to memory. The payload may be running with the D-cache on (Phase 1's
     * ICACHE_DCACHE), in which case everything above is sitting dirty in the cache - and XNU will
     * read it through page tables it is about to write itself, which the payload's cache does not
     * know about. The I-cache matters separately: the copy has just put *instructions* at
     * addresses nothing has ever executed from, and a stale line there would be fetched instead.
     *
     * Both calls exist because of Phase 1, and this is the first place either is load-bearing for
     * something other than the payload's own correctness.
     */
    cache_clean_dcache_range(STAGE90_XNU_ENTRY_BASE, STAGE90_XNU_ENTRY_SIZE);
    cache_invalidate_icache_all();
    xnu_log_puts("xnu_entry: image, bss and boot_args written back and instruction cache invalidated\n");

    r->checks = 5u;
    r->failures = 0u;
    r->status = STAGE90_STATUS_OK;
    r->checksum = stage90_xnu_entry_checksum(r);
    stage90_xnu_entry_log(r);

    /*
     * 5. The jump. r0 = boot_args, r1 = entry. Nothing after this line executes in the payload.
     */
    xnu_log_kv32("xnu_entry_entering_at", STAGE90_XNU_ENTRY_ENTRY);
    xnu_log_puts("stage90 xnu_entry: jumping to XNU's _start\n");

    xnu_entry_jump(ENTRY_ARGS_PA, STAGE90_XNU_ENTRY_ENTRY);
}

void stage90_xnu_entry_log(const struct stage90_xnu_entry_result *r)
{
    xnu_log_puts("stage90 xnu_entry result:\n");
    xnu_log_kv32("xnu_entry_version", r->version);
    xnu_log_kv32("xnu_entry_status", r->status);
    xnu_log_kv32("xnu_entry_base", r->entry_base);
    xnu_log_kv32("xnu_entry_va", r->entry_va);
    xnu_log_kv32("xnu_entry_image_bytes", r->image_bytes);
    xnu_log_kv32("xnu_entry_bss_start", r->bss_start);
    xnu_log_kv32("xnu_entry_bss_end", r->bss_end);
    xnu_log_kv32("xnu_entry_args_pa", r->args_pa);
    xnu_log_kv32("xnu_entry_top_of_kernel_data", r->top_of_kernel_data);
    xnu_log_kv32("xnu_entry_checks", r->checks);
    xnu_log_kv32("xnu_entry_failures", r->failures);
    xnu_log_kv32("xnu_entry_checksum", r->checksum);
}

const struct stage90_xnu_entry_result *stage90_xnu_entry_result(void)
{
    return &g_result;
}
