/*
 * Enter XNU. For real.
 *
 * Every other switch in this project runs XNU *code* - five pexpert objects, one subsystem at a
 * time - inside the payload's own context, on the payload's own page tables, with the payload's
 * own scheduler-less runtime underneath. This one does something categorically different: it
 * copies a linked image containing XNU's own `_start` to a base of its own, hands it a
 * `boot_args`, and jumps to it. From that instruction onward the page tables, the vectors, the
 * caches and the MMU state are XNU's, not ours, and this payload never runs again.
 *
 * What makes that possible at all is experiment-103's finding: `_start` does not want a page
 * table from us, it *builds* one. It needs a `boot_args` describing where it was linked and a
 * writable, aligned `topOfKernelData` with room - and then it does the rest itself. So the
 * payload's job here is small and entirely mechanical:
 *
 *   1. map the window it is about to use, because the payload's identity table covers only the
 *      first two megabytes (mmu.c does that step, gated on this switch);
 *   2. copy the entry image in and zero its BSS;
 *   3. publish both, because with caches on the payload's writes may still be dirty, and XNU will
 *      read them through an MMU it has just re-pointed at the same physical memory;
 *   4. build the `boot_args`  **inside** that window, so it is readable on both sides of the page
 *      table switch;
 *   5. jump.
 *
 * The base and the `boot_args` together make every `LOAD_PHYS_ADDR` conversion inside `_start` an
 * identity - `physBase == virtBase` - which is what lets the entry image's own epilogue turn the
 * MMU off and keep executing from the same addresses.
 *
 * What you should expect to see in `/proc/last_kmsg` if it works
 * ------------------------------------------------------------
 *   ...                                                     <- everything the payload logged
 *   MI4IOS6_STAGE90_XNU xnu_entry: jumping to XNU's _start at 0x00200074
 *   MI4IOS6_STAGE90_XNU real XNU entry: _start ran to completion and branched to arm_init
 *   ...                                                     <- then platform_reboot
 *
 * The second line is written by code in the entry image, with the MMU off, after `_start` has
 * done everything a kernel entry point does. It is the whole result.
 *
 * What you should expect if it fails
 * ----------------------------------
 * A line naming the vector instead - `exception: prefetch abort`, `exception: data abort` and so
 * on - because `_start` installs exception vectors in the entry image before it switches tables,
 * and those stubs report which one fired. A hang with neither line is also possible: in that case
 * the payload never got as far as the jump, and the log ends at the last line it wrote. Both nets
 * are armed, so a hang costs a watchdog reset rather than a power press.
 *
 * What this deliberately does NOT do
 * ----------------------------------
 * It does not arm the software dead-man across the jump. The dead-man needs the payload's GIC
 * and vector state, and both are gone the moment `_start` switches tables; leaving it armed would
 * be a claim that cannot be honoured. The hardware watchdog is what covers this window, and it
 * covers it for the reason it exists - it needs nothing from the CPU's configuration at all.
 */

#include "stage90.h"
#include "xnu_arm_entry.h"

/*
 * The entry image, generated by xnu_arm_boot/build_entry.sh. It carries XNU's `_start` and the
 * symbols `_start` needs; see xnu_arm_boot/entry_stubs.c for what those are and why they can
 * report their own failure.
 */
extern const uint8_t stage90_xnu_entry_blob[];
extern const uint32_t stage90_xnu_entry_blob_size;

#define ENTRY_ARGS_OFFSET   0x00007000u   /* boot_args copy, inside the window, below the tables */
#define ENTRY_ARGS_PA       (STAGE90_XNU_ENTRY_BASE + ENTRY_ARGS_OFFSET)

static struct stage90_xnu_entry_result g_result;

/*
 * The jump itself. r0 is already the argument (AAPCS), so this is `bx r1` with a guard behind it
 * so a mistake cannot fall through into whatever the compiler put next.
 *
 * `naked` because a compiler-generated prologue would touch the stack, and after the jump the
 * stack is XNU's; the arguments are taken in registers. It does not return, ever.
 */
__attribute__((naked, noreturn)) static void xnu_entry_jump(uint32_t boot_args_pa, uint32_t entry)
{
    /* The two parameters are AAPCS r0 and r1; naming them documents the call and the linker
     * needs no more, but the body cannot refer to them (naked), hence the casts. */
    (void)boot_args_pa;
    (void)entry;
    __asm__ volatile (
        "bx     r1\n\t"
        "1:     b   1b\n\t"
    );
}

static void xnu_entry_build_args(void)
{
    /*
     * Written at the physical address directly - the window is identity-mapped, so the pointer and
     * the PA are the same number, and saying it as a PA is what makes that obvious rather than
     * incidental.
     */
    struct boot_args *a = (struct boot_args *)(uintptr_t)ENTRY_ARGS_PA;

    memset(a, 0, sizeof(*a));
    a->Revision = BOOT_ARGS_REVISION;
    a->Version = BOOT_ARGS_VERSION;
    /*
     * physBase == virtBase is the whole trick. `_start` computes `addr - virtBase + physBase` for
     * every symbol it uses, so equal values make that the identity and let the entry image keep
     * running after it maps itself and after it later unmaps itself.
     */
    a->virtBase = STAGE90_XNU_ENTRY_BASE;
    a->physBase = STAGE90_XNU_ENTRY_BASE;
    /* 2 MB: the whole window, so `_start`'s section loop covers the image and the tables. */
    a->memSize = STAGE90_XNU_ENTRY_SIZE;
    /* 16 KB aligned, above the image and its BSS, inside the span, with room for L1+L2+HIGH pages. */
    a->topOfKernelData = STAGE90_XNU_ENTRY_BASE + 0x00020000u;
    a->machineType = 0x00009074u;
    a->deviceTreeP = 0;              /* outside the window; `_start` does not read it */
    a->deviceTreeLength = 0u;
    a->bootFlags = 0u;
    a->memSizeActual = STAGE90_XNU_ENTRY_SIZE;

    xnu_log_kv32("xnu_entry_args_pa", ENTRY_ARGS_PA);
    xnu_log_kv32("xnu_entry_args_virtBase", a->virtBase);
    xnu_log_kv32("xnu_entry_args_physBase", a->physBase);
    xnu_log_kv32("xnu_entry_args_memSize", a->memSize);
    xnu_log_kv32("xnu_entry_args_topOfKernelData", a->topOfKernelData);
}

int stage90_xnu_entry_run(void)
{
    struct stage90_xnu_entry_result *r = &g_result;
    uint8_t *dest = (uint8_t *)(uintptr_t)STAGE90_XNU_ENTRY_BASE;

    memset(r, 0, sizeof(*r));
    r->version = STAGE90_XNU_ENTRY_VERSION;
    r->size = sizeof(*r);
    r->entry_base = STAGE90_XNU_ENTRY_BASE;
    r->entry_va = STAGE90_XNU_ENTRY_ENTRY;
    r->image_bytes = stage90_xnu_entry_blob_size;
    r->bss_start = STAGE90_XNU_ENTRY_BSS_START;
    r->bss_end = STAGE90_XNU_ENTRY_BSS_END;
    r->args_pa = ENTRY_ARGS_PA;
    r->top_of_kernel_data = STAGE90_XNU_ENTRY_BASE + 0x00020000u;

    xnu_log_puts("stage90 xnu_entry: entering XNU - this is the last thing the payload does\n");

    /*
     * Refuse rather than guess if the image does not fit where the linker script and the
     * boot_args both say it is. A mismatch here would surface as `_start` executing whatever
     * happened to be at the base, which is the least debuggable failure available.
     */
    if (stage90_xnu_entry_blob_size == 0u ||
        STAGE90_XNU_ENTRY_ENTRY < STAGE90_XNU_ENTRY_BASE ||
        STAGE90_XNU_ENTRY_ENTRY >= STAGE90_XNU_ENTRY_BASE + STAGE90_XNU_ENTRY_SIZE ||
        STAGE90_XNU_ENTRY_BSS_END > STAGE90_XNU_ENTRY_BASE + 0x00020000u) {
        xnu_log_puts("xnu_entry: the linked image does not match the window it is copied to\n");
        r->status = STAGE90_STATUS_BASE;
        r->checksum = stage90_xnu_entry_checksum(r);
        stage90_xnu_entry_log(r);
        return -1;
    }

    /* 1. the image */
    memcpy(dest, stage90_xnu_entry_blob, stage90_xnu_entry_blob_size);
    xnu_log_kv32("xnu_entry_copied_to", STAGE90_XNU_ENTRY_BASE);
    xnu_log_kv32("xnu_entry_copied_bytes", stage90_xnu_entry_blob_size);

    /* 2. its BSS, which objcopy does not carry in a binary */
    memset((void *)(uintptr_t)STAGE90_XNU_ENTRY_BSS_START, 0,
           STAGE90_XNU_ENTRY_BSS_END - STAGE90_XNU_ENTRY_BSS_START);
    xnu_log_kv32("xnu_entry_bss_bytes", STAGE90_XNU_ENTRY_BSS_END - STAGE90_XNU_ENTRY_BSS_START);

    /* 3. the boot_args, inside the window */
    xnu_entry_build_args();

    /*
     * 4. publish both to memory. The payload may be running with the D-cache on (Phase 1's
     * ICACHE_DCACHE), in which case everything above is sitting dirty in the cache - and XNU will
     * read it through page tables it is about to write itself, which the payload's cache does not
     * know about. The I-cache matters separately: the copy has just put *instructions* at
     * addresses nothing has ever executed from, and a stale line there would be fetched instead.
     *
     * Both calls exist because of Phase 1, and this is the first place either is load-bearing for
     * something other than the payload's own correctness.
     */
    cache_clean_dcache_range(STAGE90_XNU_ENTRY_BASE, STAGE90_XNU_ENTRY_SIZE);
    cache_invalidate_icache_all();
    xnu_log_puts("xnu_entry: image, bss and boot_args written back and instruction cache invalidated\n");

    r->checks = 5u;
    r->failures = 0u;
    r->status = STAGE90_STATUS_OK;
    r->checksum = stage90_xnu_entry_checksum(r);
    stage90_xnu_entry_log(r);

    /*
     * 5. The jump. r0 = boot_args, r1 = entry. Nothing after this line executes in the payload.
     */
    xnu_log_kv32("xnu_entry_entering_at", STAGE90_XNU_ENTRY_ENTRY);
    xnu_log_puts("stage90 xnu_entry: jumping to XNU's _start\n");

    xnu_entry_jump(ENTRY_ARGS_PA, STAGE90_XNU_ENTRY_ENTRY);
}

void stage90_xnu_entry_log(const struct stage90_xnu_entry_result *r)
{
    xnu_log_puts("stage90 xnu_entry result:\n");
    xnu_log_kv32("xnu_entry_version", r->version);
    xnu_log_kv32("xnu_entry_status", r->status);
    xnu_log_kv32("xnu_entry_base", r->entry_base);
    xnu_log_kv32("xnu_entry_va", r->entry_va);
    xnu_log_kv32("xnu_entry_image_bytes", r->image_bytes);
    xnu_log_kv32("xnu_entry_bss_start", r->bss_start);
    xnu_log_kv32("xnu_entry_bss_end", r->bss_end);
    xnu_log_kv32("xnu_entry_args_pa", r->args_pa);
    xnu_log_kv32("xnu_entry_top_of_kernel_data", r->top_of_kernel_data);
    xnu_log_kv32("xnu_entry_checks", r->checks);
    xnu_log_kv32("xnu_entry_failures", r->failures);
    xnu_log_kv32("xnu_entry_checksum", r->checksum);
}

const struct stage90_xnu_entry_result *stage90_xnu_entry_result(void)
{
    return &g_result;
}
