#!/bin/bash
#
# Build the payload's real device-tree builder for the HOST and dump the blob it produces.
#
#     tools/apple_dt_host_dump.sh [outdir]        # default out/apple_dt_host
#
# Why this exists, and why it is a *build* rather than a re-implementation. Experiment 440's run
# ended in `pexpert/gen/device_tree.c:56`'s overflow panic, from `next_prop()` - which means some
# property in the tree has a `length` that cannot be a length. The tree is built on the device by
# `build_stage90_apple_dt()` in `stages/stage90/stage90_main.c`, and every node's property count is
# written **by hand** at `apple_dt_node_begin(b, N, C)` while the N properties below it are separate
# statements. A count that has drifted from the statements it counts is invisible to a reader and
# fatal to an exhaustive walk, and XNU's `DTIterateProperties` (reached only from IOKit's
# `MakeReferenceTable`) is the first *exhaustive* property walk this tree has ever had.
#
# The alternative - re-implementing the builder in Python - would measure the re-implementation. So
# the builder's **own source text** is sliced out of `stage90_main.c` by line range and compiled
# together with the real `apple_dt.c`, and the blob this writes is the blob the device builds. The
# only thing that differs is `stage90_xnu_consistent_debug_region_init()`'s return value, which is a
# pointer into the payload's own memory: the dump says so in its own header, and `--debug-root`
# substitutes the device's value into the one property that carries it so the blob is byte-exact.
#
# The slice is checked rather than trusted: the first and last line of each range are asserted to be
# the braces and declarations the range is supposed to start and end with, so a `stage90_main.c` edit
# that moves the function fails this script instead of silently dumping a different tree.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$REPO_ROOT/stages/stage90/stage90_main.c"
OUT="${1:-$REPO_ROOT/out/apple_dt_host}"
DEBUG_ROOT="${STAGE90_DEBUG_ROOT_VAL:-0}"

mkdir -p "$OUT"

# The builder's extent, and each end is asserted below. `g_apple_dt` is line 4 (the builder passes it
# to apple_dt_begin, so it is part of the slice), `build_chosen_random_seed` is 34-41 with its
# `#define` and its rule string at 31-32, and `build_stage90_apple_dt` is 43-831.
SEED_RANGE=5,41
BUILDER_RANGE=43,831

line() { sed -n "${1}p" "$SRC"; }

if ! line 4 | grep -q 'g_apple_dt\[32768\]'; then
    echo "FAIL: line 4 of stage90_main.c is not the apple-dt buffer:" >&2
    line 4 >&2
    exit 1
fi
if ! line 31 | grep -q 'STAGE90_CHOSEN_RANDOM_SEED_BYTES 64u'; then
    echo "FAIL: line 31 of stage90_main.c is not the random-seed length:" >&2
    line 31 >&2
    exit 1
fi
if ! line 34 | grep -q 'static void build_chosen_random_seed'; then
    echo "FAIL: line 34 of stage90_main.c is not build_chosen_random_seed's declaration:" >&2
    line 34 >&2
    exit 1
fi
if [[ "$(line 41)" != "}" ]]; then
    echo "FAIL: line 41 of stage90_main.c does not close build_chosen_random_seed:" >&2
    line 41 >&2
    exit 1
fi
if ! line 43 | grep -q 'static void build_stage90_apple_dt(struct apple_dt_builder \*b)'; then
    echo "FAIL: line 43 of stage90_main.c is not build_stage90_apple_dt's definition:" >&2
    line 43 >&2
    exit 1
fi
if [[ "$(line 831)" != "}" ]]; then
    echo "FAIL: line 831 of stage90_main.c does not close build_stage90_apple_dt:" >&2
    line 831 >&2
    exit 1
fi

# The slice, taken as text. `#line` is NOT used: the point is that a compiler error in here has to be
# read against the real file, and the range is printed in the dump header for exactly that.
{
    echo "/* Sliced from stages/stage90/stage90_main.c: lines 4-41 and 43-831."
    echo " * Generated by tools/apple_dt_host_dump.sh - do not edit. */"
    sed -n '4,41p' "$SRC"
    sed -n '43,831p' "$SRC"
} > "$OUT/builder.inc"

# `align4` is the builder's only other dependency, and it is one line in stages/stage90/runtime.c.
# The body is copied rather than re-invented, and compared against the real source so a change there
# fails this script rather than making the dump a different tree.
if ! grep -q 'return (v + 3u) & ~3u;' "$REPO_ROOT/stages/stage90/runtime.c"; then
    echo "FAIL: runtime.c's align4 is not the one-line definition this harness copies." >&2
    grep -n -A3 '^uint32_t align4' "$REPO_ROOT/stages/stage90/runtime.c" >&2
    exit 1
fi

cat > "$OUT/harness.c" <<HARNESS
/*
 * Host harness for the payload's device-tree builder. See tools/apple_dt_host_dump.sh.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#include "stage90.h"

/* The builder's only two external dependencies that are not apple_dt_*. Both are logging in the
 * payload; on the host they are silent, and neither changes a byte of the tree. */
void log_puts(const char *s) { (void)s; }
void log_kv32(const char *key, uint32_t value) { (void)key; (void)value; }

/* stages/stage90/runtime.c:58-61, asserted above. */
uint32_t align4(uint32_t v) { return (v + 3u) & ~3u; }

/*
 * The one value that is the payload's own memory rather than a constant: the property
 * \`consistent-debug-root\` carries this address. \`--debug-root\` substitutes the device's value so the
 * dumped blob is byte-exact; with the default 0 the blob differs from the device's in those four
 * bytes and nowhere else, and a walk cannot see a value.
 */
uint32_t stage90_xnu_consistent_debug_region_init(void) { return ${DEBUG_ROOT}u; }

#include "builder.inc"
#include "$REPO_ROOT/stages/stage90/apple_dt.c"

int main(int argc, char **argv)
{
    const char *path = (argc > 1) ? argv[1] : "apple_dt.bin";
    static struct apple_dt_builder b;
    uint32_t len;

    build_stage90_apple_dt(&b);
    len = apple_dt_finish(&b);
    if (len == 0u) {
        fprintf(stderr, "apple_dt_finish reported a builder error\\n");
        return 1;
    }
    FILE *fh = fopen(path, "wb");
    if (!fh) { perror(path); return 1; }
    if (fwrite(g_apple_dt, 1, len, fh) != len) { perror("fwrite"); return 1; }
    fclose(fh);
    printf("%u\\n", len);
    return 0;
}
HARNESS

gcc -std=gnu11 -O1 -Wall \
    -I "$REPO_ROOT/stages/stage90" \
    -o "$OUT/apple_dt_dump" "$OUT/harness.c"

"$OUT/apple_dt_dump" "$OUT/apple_dt.bin" > "$OUT/len.txt"
echo "blob: $OUT/apple_dt.bin ($(cat "$OUT/len.txt") bytes)"
