#!/usr/bin/env python3
"""
The headers Apple's config(8) generates from `device` / `pseudo-device` declarations.

    XNU_KERNEL_CONFIG=RELEASE ./tools/gen_device_headers.py            # write them
    XNU_KERNEL_CONFIG=RELEASE ./tools/gen_device_headers.py --check    # refuse a stale one
    ./tools/gen_device_headers.py --print-path

Why this is generated rather than written. `mkheaders.c`'s `headers()` walks the file table and calls
`do_count(fl->f_needs, fl->f_needs, 1)` for **every** `conf/files` line that has a need, and
`do_count` (mkheaders.c:85-101) finds the device in `dtab` and writes

    count = dp->d_slave != UNKNOWN ? dp->d_slave : 1;
    #define N<COND> <count>        into    <cond>.h

so the file name is the **first need word** of the `optional` clause and the macro is that word
upper-cased with an `N`. Two consequences that the hand-written version could not express:

  * **the emitted set is an intersection** — a condition that is a device *and* is tested by some
    `optional` clause. `mdevdevice`, `fsevents` and `random` are devices of this configuration and no
    `conf/files` line tests them (`randomdev.c`, `memdev.c` and `vfs_fsevents.c` are `standard`), so
    they get **no header** — and `gen_device_headers.sh` agreed by omitting them, by hand.
  * **the value is the declaration's own number.** `pseudo-device pty 16` is `#define NPTY 16`. The
    hand-written file said `NPTY 1`, with a comment explaining that `tty_pty.c:88` promotes 1 to 32
    "which is why 1 is the value that both compiles the file and satisfies the macro's own
    expectation". It compiles either way; 1 is not the value the configuration chose, and the
    `pseudo_inits[]` array this image walks already passed **16** to `pty_init`. Two definitions of
    one number, and one of them was hand-written.

**What the old file was right about, kept because it is still the reason the values matter:** a
header missing from the include path is not an error here, it is the *host's* header.
`bsd/dev/arm/conf.c:111`'s `#include <pty.h>` with no `pty.h` anywhere on the path resolved to
`/usr/include/pty.h` — the target is an ELF triple whose driver sysroot is `/`, so glibc's headers
are reachable — and the file died in `features-time64.h: 'bits/wordsize.h' file not found`, naming
neither XNU nor the header that was really absent (experiment-166).

**And the value has to agree with whether the file is compiled**, which is why the emitted set and
the values come from the same parse the manifest's table uses (`tools/xnu_config/devices.py`):
`bsd/kern/bsd_init.c:875` is `#include <loop.h>` with `#if NLOOP > 0 / loopattach();` inside the
function, and `:890` is `#if NETHER > 0 / ether_family_init();`. A manifest that builds
`bsd/net/if_loop.c` while the header says `NLOOP 0` leaves `loopattach` defined and never called —
inconsistent in the quiet direction — and one that does not build it while the header says `NLOOP 1`
is an undefined symbol. The two are checked against each other by
`tools/check_device_conditions.py`, and this generator rewrites the directory every run so a stale
header cannot survive a configuration change.
"""

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
XNU = os.environ.get("XNU_TREE", os.path.join(REPO_ROOT, "external", "xnu-4570.1.46"))

sys.path.insert(0, os.path.join(HERE, "xnu_config"))
import devices as devices_mod                                                     # noqa: E402
import device_table as table_mod                                                  # noqa: E402

CONFIG = os.environ.get("XNU_KERNEL_CONFIG", "RELEASE")
OUT_ROOT = os.environ.get("XNU_DEVICE_HEADERS_OUT", os.path.join(REPO_ROOT, "out", "xnu_device"))


def out_dir(config):
    """Per configuration, and a function for the same reason `gen_pseudo_inits.py`'s `out_file` is:
    one definition of the path, so `--print-path`, `--check` and the writer cannot disagree."""
    return os.path.join(OUT_ROOT, config)


def emitted(config):
    """[(condition, count)] — the intersection of `dtab` and the `conf/files` need words.

    In `conf/files` order, because that is the order `headers()` walks the file table in.
    """
    declared = {name.lower(): number
                for name, number, _init, _kind in devices_mod.devices(config)}
    tested = table_mod.conditions()
    return [(cond, devices_mod.header_count(declared[cond]))
            for cond in sorted(tested) if cond in declared]


def render(config, cond, count):
    macro = "N" + cond.upper()
    kind = "a count" if count not in (0, 1) else "a flag"
    return f"""/* Generated by tools/gen_device_headers.py for the {config} configuration.
 *
 * `mkheaders.c:85-101` writes one of these per `conf/files` need word that names a device in
 * `dtab`: the file is `<word>.h` and the macro is the word upper-cased with an `N`. `{cond}` is
 * {kind} here, and the value is the configuration's own
 * declaration — `count = d_slave != UNKNOWN ? d_slave : 1` — read from
 * `tools/xnu_config/expand.sh {config}`.
 *
 * A bare `pseudo-device {cond}` has no number, which is `d_slave == UNKNOWN` and becomes 1; an
 * explicit `pseudo-device {cond} N` keeps its N. Both are the declaration's, not this file's.
 */
#define {macro} {count}
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--config", default=CONFIG)
    ap.add_argument("--check", action="store_true",
                    help="fail when a header on disk is not what the configuration derives")
    ap.add_argument("--print-path", action="store_true")
    args = ap.parse_args()

    path = out_dir(args.config)
    if args.print_path:
        print(path)
        return 0

    rows = emitted(args.config)
    if not rows:
        sys.exit(f"the {args.config} configuration declares no device that any conf/files line "
                 f"tests - that is not a configuration this project has ever built, so it is an "
                 f"error and not an empty set")

    wanted = {f"{cond}.h": render(args.config, cond, count) for cond, count in rows}

    if args.check:
        stale = []
        for name, text in sorted(wanted.items()):
            try:
                on_disk = open(os.path.join(path, name)).read()
            except FileNotFoundError:
                stale.append(f"{name} is missing")
                continue
            if on_disk != text:
                stale.append(f"{name} is not what the {args.config} configuration derives")
        for name in sorted(os.listdir(path) if os.path.isdir(path) else []):
            if name.endswith(".h") and name not in wanted:
                stale.append(f"{name} is for a condition this configuration does not have")
        if stale:
            print(f"device headers are not current for {args.config}:", file=sys.stderr)
            for s in stale:
                print(f"  {s}", file=sys.stderr)
            print(f"run: XNU_KERNEL_CONFIG={args.config} ./tools/gen_device_headers.py",
                  file=sys.stderr)
            return 1
        print(f"ok: {len(rows)} device header(s) for {args.config} - "
              + ", ".join(f"N{cond.upper()}={count}" for cond, count in rows))
        return 0

    os.makedirs(path, exist_ok=True)
    # The directory is rewritten, not merged: a header left over from a condition this
    # configuration no longer has would be found on the include path and believed, which is the
    # silent direction of the same defect the missing-header case was loud about.
    for name in sorted(os.listdir(path)):
        if name.endswith(".h") and name not in wanted:
            os.unlink(os.path.join(path, name))
            print(f"removed {name} (no longer a condition of {args.config})")
    for name, text in sorted(wanted.items()):
        with open(os.path.join(path, name), "w") as fh:
            fh.write(text)

    print(f"wrote {len(rows)} device header(s) for {args.config} in {path}")
    for cond, count in rows:
        print(f"  {cond}.h\t#define N{cond.upper()} {count}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
