#!/usr/bin/env bash
#
# The headers Apple's config(8) generates from `device` / `pseudo-device` declarations.
#
#   XNU_KERNEL_CONFIG=RELEASE ./tools/gen_device_headers.sh
#   XNU_KERNEL_CONFIG=STAGE90_BOOT ./tools/gen_device_headers.sh
#
# This is the third generator, alongside the `OPTIONS/` macros (gen_option_headers.py) and
# `libkern/version.h` (gen_libkern_version.sh), and it writes **four** headers — `loop.h`, `pty.h`,
# `ptmx.h`, `bpfilter.h` — one per device-table entry a configuration needs and 4570 does not
# publish.
#
# **It is per configuration**, into `out/xnu_device/$CONFIG`, for the same reason the `OPTIONS/`
# headers are: a device table is a property of the configuration, and `bpfilter.h` is 0 here and
# would be a count in one that sets `bpfilter`. And `build_xnu_arm_kernel.sh` now refuses to start
# without this configuration's directory, because the absence of one is **not an error** — a header
# missing from the include path falls through to the *host's*, which is what happened while only
# `RELEASE` had one: `bsd/dev/arm/conf.c:111`'s `#include <pty.h>` resolved to `/usr/include/pty.h`
# and the file died in glibc's `features-time64.h`, naming neither XNU nor the absent header
# (experiment-166).
#
# `bsd/kern/bsd_init.c:875` is `#include <loop.h>` — inside the function, with
# `#if NLOOP > 0 / loopattach();` on the next lines. `bsd/netinet6/ip6_input.c:154` says "we need it
# for NLOOP" and includes it too, and `in6_src.c` and `nd6.c` follow. Four files, and the header is
# not in the tarball because **config(8) writes it**: `pseudo-device loop` in a kernel configuration
# becomes `#define NLOOP 1` in `loop.h`.
#
# But 4570 ships no `device` or `pseudo-device` lines at all — verified: `grep -c '^pseudo-device'
# */conf/files` is 0 in every component — so the device tables that would say `NLOOP 1` are not
# published, exactly as `MONOTONIC` was not (experiment-112) and the per-SoC build definitions are
# not (experiment-113). NLOOP is therefore a **choice**, and the honest one to record is 0:
#
#   * `#if NLOOP > 0` then excludes `loopattach()` and the rest of the loopback attach path —
#     strictly less code at runtime, which is the same reasoning `MACH_ASSERT 0`, `ZONE_DEBUG 0` and
#     the minimal configuration all use;
#   * `bsd/net/if_loop.c` is `optional loop` and `loop` is not a set option, so that file is not in
#     the manifest and nothing would provide `loopattach()` anyway. With NLOOP 1 this would be an
#     undefined symbol at link time; with NLOOP 0 it is not referenced.
#
# The second point is the one that makes this a decision rather than a guess: **the value has to
# agree with whether the file is compiled**, and it is not.

set -uo pipefail
cd "$(dirname "$0")"
TOOLS_DIR=$PWD
REPO_ROOT=$(cd "$TOOLS_DIR/.." && pwd)

CONFIG=${XNU_KERNEL_CONFIG:-RELEASE}
OUT=${XNU_DEVICE_HEADERS_OUT:-$REPO_ROOT/out/xnu_device}/$CONFIG

mkdir -p "$OUT"

cat > "$OUT/loop.h" <<'EOF'
/* Generated by tools/gen_device_headers.sh - see that file for why this is a choice.
 *
 * `pseudo-device loop` in an Apple kernel configuration becomes `#define NLOOP 1` here. 4570
 * publishes no device tables, so the value is chosen: 0 matches a configuration that does not build
 * bsd/net/if_loop.c (`optional loop`, and `loop` is not set), which is what makes the reference to
 * loopattach() go away rather than become an undefined symbol. */
#define NLOOP 0
EOF

# `pty.h`, the same shape, and the value is measured rather than chosen. `NPTY 0` was tried and does
# NOT compile: `bsd/dev/arm/conf.c:112` is `#if NPTY > 0` and its `#else` branch defines `ptcselect`
# but not `ptsselect`, which exists nowhere in the tree - so Apple's zero case is a source defect on
# a path their configuration never takes (experiment-130). The device has to be on. `NPTY 1` is what
# the sources expect: `bsd/kern/tty_pty.c:89-92` promotes 1 to 32 with a `#warning`, so 1 is both the
# value that compiles the file and the one its own code anticipates.
cat > "$OUT/pty.h" <<'EOF'
/* Generated by tools/gen_device_headers.sh - see that file for why this is 1 and not 0.
 *
 * `pseudo-device pty N` in an Apple kernel configuration becomes `#define NPTY <N>` here. 4570
 * publishes no device tables, so the value comes from experiment-130's measurement: NPTY 0 does not
 * compile (conf.c's #else branch is missing ptsselect), and tty_pty.c promotes 1 to 32 itself. */
#define NPTY 1
EOF

cat > "$OUT/ptmx.h" <<'EOF'
/* Generated by tools/gen_device_headers.sh - same reasoning as pty.h. `bsd/kern/tty_dev.c` is
 * `optional ptmx pty`, so it needs both, and `bsd/kern/tty_ptmx.c` is `optional ptmx`. */
#define NPTMX 1
EOF

# `bpfilter.h`, and this one is a *count* rather than a 0/1 - which is why the source tests it as
# one. `bsd/net/net_osdep.h:212-215` records the convention: "number of bpf pseudo devices: others:
# bpfilter.h, NBPFILTER". `bsd/net/if_bridge.c:134` is `#if NBPFILTER > 0 / #include <net/bpf.h>` and
# `:1419` uses `DLT_EN10MB` **outside** that guard.
#
# The value has to agree with whether `bpfilter` is set, exactly as `NLOOP`/`NPTY` do, and it does
# not: `RELEASE` sets `if_bridge` and not `bpfilter`, so `bpf.h` is not included and the unguarded use
# fails. That is a source path valid only with the option built - the third instance of the shape
# `ptsselect` (experiment-130) and `loop.h` belong to.
#
# **Recorded rather than turned on.** `NBPFILTER 1` would make `if_bridge.c` compile and would not be
# honest on its own: `bsd/net/bpf.c` is `optional bpfilter`, so the option must be set too, which pulls
# the packet-filter machinery into a configuration built for a first boot. A configuration decision,
# not a header value.
cat > "$OUT/bpfilter.h" <<'EOF'
/* Generated by tools/gen_device_headers.sh.
 *
 * `pseudo-device bpfilter N` in an Apple kernel configuration becomes `#define NBPFILTER <N>` here -
 * a COUNT, per bsd/net/net_osdep.h:212-215, which is why the sources test `NBPFILTER > 0` rather than
 * treating it as a flag. 0 matches this configuration, which does not build bsd/net/bpf.c
 * (`optional bpfilter`).
 *
 * One consequence is a source path that does not compile: bsd/net/if_bridge.c:1419 uses DLT_EN10MB
 * outside its `#if NBPFILTER > 0` guard, so that file needs the option on. */
#define NBPFILTER 0
EOF

echo "generated 4 device headers (NLOOP 0, NPTY 1, NPTMX 1, NBPFILTER 0) in $OUT"