#!/usr/bin/env bash
#
# The headers Apple's config(8) generates from `device` / `pseudo-device` declarations.
#
#   ./tools/gen_device_headers.sh
#
# This is the third generator, alongside the `OPTIONS/` macros (gen_option_headers.py) and
# `libkern/version.h` (gen_libkern_version.sh), and there is exactly one header in it today.
#
# `bsd/kern/bsd_init.c:875` is `#include <loop.h>` — inside the function, with
# `#if NLOOP > 0 / loopattach();` on the next lines. `bsd/netinet6/ip6_input.c:154` says "we need it
# for NLOOP" and includes it too, and `in6_src.c` and `nd6.c` follow. Four files, and the header is
# not in the tarball because **config(8) writes it**: `pseudo-device loop` in a kernel configuration
# becomes `#define NLOOP 1` in `loop.h`.
#
# But 4570 ships no `device` or `pseudo-device` lines at all — verified: `grep -c '^pseudo-device'
# */conf/files` is 0 in every component — so the device tables that would say `NLOOP 1` are not
# published, exactly as `MONOTONIC` was not (experiment-112) and the per-SoC build definitions are
# not (experiment-113). NLOOP is therefore a **choice**, and the honest one to record is 0:
#
#   * `#if NLOOP > 0` then excludes `loopattach()` and the rest of the loopback attach path —
#     strictly less code at runtime, which is the same reasoning `MACH_ASSERT 0`, `ZONE_DEBUG 0` and
#     the minimal configuration all use;
#   * `bsd/net/if_loop.c` is `optional loop` and `loop` is not a set option, so that file is not in
#     the manifest and nothing would provide `loopattach()` anyway. With NLOOP 1 this would be an
#     undefined symbol at link time; with NLOOP 0 it is not referenced.
#
# The second point is the one that makes this a decision rather than a guess: **the value has to
# agree with whether the file is compiled**, and it is not.

set -uo pipefail
cd "$(dirname "$0")"
TOOLS_DIR=$PWD
REPO_ROOT=$(cd "$TOOLS_DIR/.." && pwd)

CONFIG=${XNU_KERNEL_CONFIG:-RELEASE}
OUT=${XNU_DEVICE_HEADERS_OUT:-$REPO_ROOT/out/xnu_device}/$CONFIG

mkdir -p "$OUT"

cat > "$OUT/loop.h" <<'EOF'
/* Generated by tools/gen_device_headers.sh - see that file for why this is a choice.
 *
 * `pseudo-device loop` in an Apple kernel configuration becomes `#define NLOOP 1` here. 4570
 * publishes no device tables, so the value is chosen: 0 matches a configuration that does not build
 * bsd/net/if_loop.c (`optional loop`, and `loop` is not set), which is what makes the reference to
 * loopattach() go away rather than become an undefined symbol. */
#define NLOOP 0
EOF

# `pty.h` is NOT generated here, and the reason is a finding rather than an omission.
#
# `bsd/dev/arm/conf.c:111` includes it unconditionally and `NPTY` gates its pts/ptc externs, so the
# same treatment as `loop.h` was tried: `#define NPTY 0`, consistent with `bsd/kern/tty_pty.c` being
# `optional pty` and `pty` not being a set option, so that file is not compiled either. Measured:
# conf.c then fails on
#
#     bsd/dev/arm/conf.c:189:36: error: use of undeclared identifier 'ptsselect'
#
# and `ptsselect` **exists nowhere in the tree** - the `#else` branch of conf.c defines `ptcselect`
# but not `ptsselect`. So Apple's `NPTY 0` path does not compile, at all, in 4570. `NPTY` must be
# non-zero for this file, and then `bsd/kern/tty_pty.c` has to be compiled with it or the link
# reports `ptsopen`, `ptcopen`, `ptyioctl` and their neighbours as undefined.
#
# That is the same shape as `loop` but with the opposite answer, and it exposes a limit of
# `list_sources.py`: `pty` is a *device*, not an option, and 4570 publishes no device tables
# (experiment-127), so `optional pty` can never match and `pty` cannot be turned on through the
# configuration fragment the way `MONOTONIC_BASE` was. Doing this properly means giving the tool a
# device table to read, not another one-line choice. Left as a recorded next step rather than
# half-implemented: `NPTY 1` alone would compile conf.c and add 7 undefined symbols at link time.

echo "generated 1 device header (NLOOP 0) in $OUT"