#!/usr/bin/env bash
#
# Link the compiled XNU objects into a real ELF, and report what the linker says besides
# "undefined symbol".
#
#   ./tools/measure_link.sh                 # RELEASE
#   ./tools/measure_link.sh --min           # STAGE90_BOOT
#   ./tools/measure_link.sh --keep-stubs    # leave out/link/<config>-stubs.s for reading
#
# Why this exists, and what it is not. `link_xnu_arm.sh` does `ld -r`, which resolves nothing and
# (correctly) refuses to produce an image. This goes one step further: it links a **final** ELF,
# with every symbol the build cannot provide stubbed as a weak function, so the linker can do the
# part of its job that has nothing to do with missing code — placing sections, applying
# relocations, checking that nothing is out of range. The stubs are not a shim and nothing boots;
# the image is a **measurement**, and its value is the two things it reports:
#
#   * **the section layout**, at XNU's own addresses (`tools/xnu_measure_link.ld`), which is the
#     first time the project has seen whether the kernel's code fits where `start.s` will map it;
#   * **every linker diagnostic that is not an undefined reference** — a branch out of range, a
#     relocation against an unrepresentable symbol, a section that will not place. `ld -r` cannot
#     produce those because it does not lay anything out.
#
# The stub count is *not* a result: it is set, by construction, to the number of undefined symbols.
# What is a result is that the count did not change between the two passes, which would mean a stub
# pulled in more missing code (a stub is a leaf; if it does not, something is wrong with the model).

set -uo pipefail
cd "$(dirname "$0")"
TOOLS_DIR=$PWD
REPO_ROOT=$(cd "$TOOLS_DIR/.." && pwd)

LD=${LD:-arm-none-eabi-ld}
AS=${AS:-arm-none-eabi-as}
NM=${NM:-arm-none-eabi-nm}
SIZE=${SIZE:-arm-none-eabi-size}
READELF=${READELF:-arm-none-eabi-readelf}

CONFIG=${XNU_KERNEL_CONFIG:-RELEASE}
KEEP_STUBS=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --min)        CONFIG=STAGE90_BOOT; shift ;;
        --keep-stubs) KEEP_STUBS=1; shift ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

if [[ $CONFIG == STAGE90_BOOT ]]; then
    OBJ=${MIN_OBJ:-$REPO_ROOT/out/xnu_min_obj}
else
    OBJ=${XNU_KERNEL_OBJ_OUT:-$REPO_ROOT/out/xnu_kernel_obj}
fi
ASM=${XNU_ASM_OBJ:-$REPO_ROOT/out/xnu_asm_obj}
OUT=${LINK_OUT:-$REPO_ROOT/out/link}
SCRIPT=$TOOLS_DIR/xnu_measure_link.ld
STUBS=$OUT/$CONFIG-stubs.s
ELF=$OUT/$CONFIG-measure.elf

[[ -d $OBJ ]] || { echo "no objects in $OBJ" >&2; exit 2; }
mkdir -p "$OUT"

mapfile -t OBJS < <(ls "$OBJ"/*.o 2>/dev/null | sort)
[[ ${#OBJS[@]} -gt 0 ]] || { echo "no .o files in $OBJ" >&2; exit 2; }
# The assembled ARM layer, when it is there. `start.s` is the entry the kernel actually has, and
# `out/xnu_asm_obj/` holds whatever `stages/stage90/xnu_arm_assemble.sh` and the build produced.
mapfile -t ASMOBJS < <(ls "$ASM"/*.o 2>/dev/null | sort)

emit_stubs() {   # $1 = undefined-symbol list, $2 = output .s
    {
        echo "/* Generated by tools/measure_link.sh. One weak definition per symbol the built"
        echo " * objects reference and none defines, so the measurement link can complete and"
        echo " * report everything ELSE the linker has to say. Not a shim, not bootable. */"
        echo "	.syntax unified"
        echo "	.arm"
        echo "	.text"
        while IFS= read -r sym; do
            [[ $sym =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
            printf '\t.weak %s\n\t.type %s, %%function\n%s:\n\tmov r0, #0\n\tbx lr\n' "$sym" "$sym" "$sym"
        done < "$1"
    } > "$2"
}

# Pass 1: link without stubs, and take the undefined set from the linker's own diagnostics.
#
# From the diagnostics and not from `nm` on the output, because when the link fails there is no
# output to run `nm` on - a first version did that, got an empty list, and therefore stubbed
# nothing. A link that fails for missing symbols is exactly the case this tool exists for.
#
# Two phrasings, and the second is the one that cost a round: `undefined reference to 'X'` covers
# most of them, but a symbol with hidden visibility fails differently -
# `hidden symbol 'X' isn't defined` - and GNU ld reports that one even when
# --unresolved-symbols=ignore-all is given. So both are collected.
"$LD" -T "$SCRIPT" "${OBJS[@]}" "${ASMOBJS[@]}" -o "$ELF" 2>"$OUT/$CONFIG-measure.err"
{
    grep -oE "undefined reference to ['\`][^'\`]*" "$OUT/$CONFIG-measure.err" | sed "s/.*['\`]//"
    grep -oE "hidden symbol ['\`][^'\`]*" "$OUT/$CONFIG-measure.err" | sed "s/.*['\`]//"
} | sort -u > "$OUT/$CONFIG-measure-undef.txt"
n1=$(wc -l < "$OUT/$CONFIG-measure-undef.txt")

emit_stubs "$OUT/$CONFIG-measure-undef.txt" "$STUBS"
"$AS" -o "$OUT/$CONFIG-stubs.o" "$STUBS" || { echo "stub assembly failed" >&2; exit 2; }

# Pass 2: link with them.
"$LD" -T "$SCRIPT" "${OBJS[@]}" "${ASMOBJS[@]}" "$OUT/$CONFIG-stubs.o" -o "$ELF" 2>"$OUT/$CONFIG-measure.err"
rc=$?

echo "== $CONFIG measurement link =="
echo "  objects:           ${#OBJS[@]} compiled + ${#ASMOBJS[@]} assembled"
echo "  undefined (pass 1): $n1"
echo "  exit (pass 2):      $rc"

if [[ $rc -ne 0 ]]; then
    echo
    echo "  the linker refused even with every undefined symbol stubbed. Diagnostics that are not"
    echo "  undefined references:"
    grep -vE "undefined reference|in function|^$" "$OUT/$CONFIG-measure.err" | head -12 | sed 's/^/    /'
    exit 1
fi

# Everything below is only reachable when the link succeeded, which is the point.
echo
echo "  == what the linker had to say, besides undefined references =="
other=$(grep -vE "undefined reference|in function|^$" "$OUT/$CONFIG-measure.err" | wc -l)
echo "    lines: $other"

echo
echo "  == section layout (XNU addresses: virtBase 0x80000000, physBase 0) =="
# `readelf -S` prints `[ 1] .text PROGBITS 80000000 010000 3fa7bb ...`; the index is one or two
# tokens depending on whether it is below ten, so it is stripped rather than counted.
"$READELF" -S "$ELF" 2>/dev/null \
    | sed 's/^ *\[ *[0-9]*\] //' \
    | awk '$1==".text" || $1==".data" || $1==".bss" {printf "    %-8s addr 0x%s  size 0x%s (%s bytes)\n", $1, $3, $5, strtonum("0x" $5)}'

echo
echo "  == image =="
"$SIZE" "$ELF" | tail -1 | sed 's/^/    /'

echo
echo "  == entry =="
"$READELF" -h "$ELF" | grep -E "Entry point|Type:" | sed 's/^/    /'

for sym in _start arm_init arm_vm_init machine_startup kernel_bootstrap rtclock_init;
do
    addr=$("$NM" --defined-only "$ELF" 2>/dev/null | awk -v s="$sym" '$3==s {print $1; exit}')
    printf '    %-20s %s\n' "$sym" "${addr:-(absent)}"
done

echo
echo "  The image is a measurement: $(($(wc -l < "$OUT/$CONFIG-measure-undef.txt"))) of its symbols are stubs."
echo "  Nothing here boots. Artifacts in $OUT/"
[[ $KEEP_STUBS -eq 0 ]] && rm -f "$STUBS"
exit 0
