#!/usr/bin/env bash
#
# Rehearse `tools/verify_revert_set.sh` with no device, no build and no copy of the parked set.
#
# Why a rehearsal and not a table in a document: a refusal that has never been shown to fire is a claim,
# and this project's record is full of checks that passed because they never ran. Every cell below
# invokes the real tool against a real directory and asserts the exit code AND a phrase of the output,
# so a cell fails loudly if a refusal becomes a silence or starts naming the wrong fault.
#
# The expensive input is real, and it is two files: a genuine park is 27 MB of build output, so the
# fixture is built from the *live* `out/stage90/` - the files the gate reads are all there - and then the
# record is rewritten to describe the copies rather than the originals. That keeps the bytes real (so a
# hash mismatch is a real hash mismatch) without carrying a park in the repository, which is also why the
# fixture directory is a temporary one and is never `/tmp/r594/frozen-payload`.
#
# The cells that matter most point the REAL record at the REAL live tree, which holds the arm the next
# press sends - and the record carries many sets, exactly one of which is that arm. So the same directory
# gets both verdicts: a pass when the set under test is the one it holds, a refusal when it is not. A
# verifier that accepted it either way would be the very defect `revert-set.txt` describes - a verdict
# about a location read as a verdict about a set.
#
# The last cell is the one that would have caught this record's first draft. The set is DEFINED as the
# files the gate reads, so the record must cover that list - and the list is derived from the gate's own
# source at run time rather than trusted from the hand-written one above, which carried eight files while
# the gate read nine.
#
# Usage: ./tools/rehearse_revert_set.sh          (exit 0 = every cell behaved as its own wording promises)

set -uo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
TOOL=$ROOT/tools/verify_revert_set.sh
RECORD=$ROOT/records/revert-set.txt
LIVE=$ROOT/out/stage90

[[ -x $TOOL ]] || { echo "no tool at $TOOL" >&2; exit 1; }
[[ -d $LIVE ]] || { echo "no live tree at $LIVE - this rehearsal needs the real build outputs" >&2; exit 1; }
# The `live-tree-matches-armed-set` cell asserts a PASS by naming the set it expects to have passed, and
# **that name is now the live tree's own answer rather than a constant - 729.** It was
# `armed-sleepless-696a0f39`, hand-written, beside a guard that checked only that the NAME was in the
# record: the guard looked in the wrong place, because a set name stays in the record for good. So every
# arm parked after that one left this cell printing FAIL while the bytes it describes were correct, and a
# rehearsal that always prints one FAIL is a rehearsal whose real refusals are unreadable. The name comes
# from `tools/resolve_arm_set.sh`, which exists because "which arm are these bytes" had three answers
# (667/668) - this was the fourth, and it was a `grep` of the record rather than of the tree.
ARMED=$(bash "$ROOT/tools/resolve_arm_set.sh" "$LIVE" 2>/dev/null | cut -f1)
[[ -n $ARMED ]] || { echo "no recorded set matches the bytes in $LIVE, so the live-tree cells have no set to name and this rehearsal would be checking a fixture instead" >&2; exit 1; }

W=$(mktemp -d /tmp/rehearse-revert.XXXXXX) || exit 1
trap 'rm -rf "$W"' EXIT

FILES="SHA256SUMS.txt stage90.bin stage90-build-config.txt stage90.elf stage90.img stage90-qcdt.img stage90_fixture.macho xnu_arm_entry.bin xnu_arm_entry-config.txt xnu_arm_entry.elf xnu_arm_entry-sources.txt"

# The record the cells verify against: the real one, retargeted at the fixture's own bytes.
mkrekord() {   # mkrekord DIR OUT
  local dir=$1 out=$2
  : > "$out"
  echo "# generated by the rehearsal from $dir - the same field set and order as the real record" >> "$out"
  local f
  for f in $FILES; do
    [[ -f $dir/$f ]] || { echo "fixture is missing $f" >&2; return 1; }
    printf 'set=fixture sha256=%s bytes=%s file=%s role=rehearsal\n' \
      "$(sha256sum "$dir/$f" | cut -d' ' -f1)" "$(stat -c%s "$dir/$f")" "$f" >> "$out"
  done
}

# ---- the fixture ---------------------------------------------------------------------------------
GOOD=$W/good
mkdir -p "$GOOD"
for f in $FILES; do cp "$LIVE/$f" "$GOOD/$f"; done
mkrekord "$GOOD" "$W/fixture-record.txt" || exit 1
# The fixture's manifest names the LIVE tree, not the fixture, because that is what the build wrote.
# That is not doctored: it is what every park's manifest does, and the narration cell reads it.

OK=0; BAD=0
cell() {  # cell NAME EXPECTED_EXIT EXPECTED_PHRASE CMD...
  local name=$1 want=$2 phrase=$3; shift 3
  local out rc
  out=$("$@" 2>&1); rc=$?
  if [[ $rc -ne $want ]]; then
    printf '  FAIL  %-22s exit=%s expected %s\n' "$name" "$rc" "$want"
    printf '%s\n' "$out" | sed 's/^/          /' | head -6
    BAD=$((BAD + 1)); return
  fi
  if [[ -n $phrase ]] && ! printf '%s' "$out" | grep -qF -- "$phrase"; then
    printf '  FAIL  %-22s exit=%s but said nothing about: %s\n' "$name" "$rc" "$phrase"
    printf '%s\n' "$out" | sed 's/^/          /' | head -6
    BAD=$((BAD + 1)); return
  fi
  printf '  ok    %-22s exit=%s  %s\n' "$name" "$rc" "$phrase"
  OK=$((OK + 1))
}

echo
echo "== the revert-set verifier, rehearsed with no device =="
echo "   tool:   $TOOL"
echo "   record: the real one, retargeted at a real fixture built from $LIVE"
echo "   fixture $GOOD  (the files the gate reads, copied from $LIVE; ${W} is removed at exit)"
echo

# 1. the honest case: the fixture's own bytes against a record that describes them
cell "good-set"            0 "VERIFIED:"                        \
  bash "$TOOL" "$GOOD" --record="$W/fixture-record.txt"
cell "good-set-a-set-name" 0 "set fixture in"                   \
  bash "$TOOL" "$GOOD" --record="$W/fixture-record.txt" --set=fixture

# 2. the cells this rehearsal exists for: one directory, more than one set, and a verdict that has to
# name which set it is about. This uses the REAL record and the REAL live tree, with no copy in between.
#
# The record carries TWO sets, and `out/stage90/` holds exactly one of them:
#
#   * `--set=armed-sleepless-696a0f39` on the live tree must PASS. This direction did not exist before
#     614: the arm the next press sends is now recorded, so the record can be pointed at the thing it
#     describes and agree with it. A record that only ever refuses cannot be told from one that is wrong
#     about everything.
#   * the same directory with every set selected must REFUSE, on `frozen-574` - same directory, same
#     invocation shape, opposite verdict once the set under test changes. That pair is the whole
#     property: **a verdict about a directory that does not name its set is not a verdict about a set**,
#     which is what `sha256sum -c` does to every park.
#
# **This cell's needle was a MECHANISM and it went red on the rung-13 arm (724).** It asked for
# `stage90-qcdt.img hashes to`, which is the verifier's *second* refusal form: the tool refuses a file
# whose recorded **size** disagrees before it hashes it, and prints `hashes to` only when the sizes
# agree and the bytes do not. Every arm before this one happened to share `stage90-qcdt.img`'s size
# with some other set in the record, so the hash form appeared and the cell stayed green while it was
# really measuring the artifact's size distribution. This arm's qcdt is 8572928 bytes and no recorded
# set shares it, so the size refusal fired for every set and the needle became unproducible - on a
# correct refusal, which is m728's shape (an assertion the extractor cannot produce) one reader over,
# and m691's (a uniform verdict is a fact about the instrument first). The needle is now
# `FAIL  stage90-qcdt.img `, which both refusal forms carry and no `ok` line does, so the cell is
# about *the file being refused* rather than about *which of the two checks refused it first*.
cell "live-tree-matches-armed-set" 0 "VERIFIED: 11 file(s) of $ARMED" \
  bash "$TOOL" "$LIVE" --set="$ARMED"
cell "live-tree-vs-the-other-set" 1 "FAIL  stage90-qcdt.img "  \
  bash "$TOOL" "$LIVE"
cell "live-tree-names-the-dir" 1 "in $LIVE"                       \
  bash "$TOOL" "$LIVE"

# 2b. The same situation built entirely out of fixtures, so the property is held without depending on
# which arm happens to be in `out/` today. A record carrying two sets over ONE directory, one of them
# describing a file the directory does not hold: the honest set must pass, the other must fail, and the
# refusal must SAY WHICH IS WHICH. The note is the whole point - without it, "this park is the park of
# another set" and "this park has rotted" look identical in the failure text, and the two readings send
# a reader to different places (a backup, or `--set=`).
TWOSET=$W/twoset-record.txt
cp "$W/fixture-record.txt" "$TWOSET"
sed 's/^set=fixture/set=other/' "$W/fixture-record.txt" \
  | sed 's|^\(set=other sha256=\)[0-9a-f]\{64\}\( bytes=[0-9]* file=stage90\.bin .*\)$|\10000000000000000000000000000000000000000000000000000000000000000\2|' \
  >> "$TWOSET"
# Guard, as everywhere else in this file: if the second set did not get written the cells below would
# assert a note about a record that carries one set, and pass or fail for the wrong reason.
[[ $(grep -c '^set=other ' "$TWOSET") -eq 11 ]] || { echo "the two-set fixture record did not get its second set (found $(grep -c '^set=other ' "$TWOSET") of 11 lines) - the cells below would be checking nothing" >&2; exit 1; }
[[ $(grep -c '^set=other sha256=0000' "$TWOSET") -eq 1 ]] || { echo "the second set does not carry the doctored stage90.bin line" >&2; exit 1; }
cell "one-set-of-two-unnamed"   1 "matches fixture exactly, and fails other" \
  bash "$TOOL" "$GOOD" --record="$TWOSET"
# The mirror, and it is the direction a reader gets wrong: naming the DIRTY set does not turn the run
# green, and must not print the note - there is no clean set to name.
cell "the-dirty-set-named"      1 "stage90.bin hashes to"          \
  bash "$TOOL" "$GOOD" --record="$TWOSET" --set=other
# 3. a one-byte edit, past the header so the file still parses as an image
BADHASH=$W/badhash
mkdir -p "$BADHASH"; for f in $FILES; do cp "$GOOD/$f" "$BADHASH/$f"; done
printf '\xff' | dd of="$BADHASH/stage90-qcdt.img" bs=1 seek=1000000 conv=notrunc status=none
cell "one-byte-edited"     1 "stage90-qcdt.img hashes to"        \
  bash "$TOOL" "$BADHASH" --record="$W/fixture-record.txt"

# 3b. the same directory, but with its OWN manifest regenerated to describe the edited bytes - so the
# manifest is self-consistent and the parked set is still not the recorded one. The tool must refuse
# anyway, because it hashes from the record and never from a manifest it finds in the target. The two
# readings are shown side by side, because the whole point of the record is that they can disagree.
SELFCON=$W/self-consistent
cp -r "$BADHASH" "$SELFCON"
# The manifest must not list itself: the redirect truncates the file before `sha256sum` opens it, so a
# self-referential line records the hash of an empty file and every check against that manifest fails on
# the manifest rather than on the bytes. That is what the first run of this cell did.
( cd "$SELFCON" && sha256sum $(printf '%s\n' $FILES | grep -v '^SHA256SUMS.txt$') > SHA256SUMS.txt )
cell "self-consistent-manifest" 1 "stage90-qcdt.img hashes to"   \
  bash "$TOOL" "$SELFCON" --record="$W/fixture-record.txt"
if ( cd "$SELFCON" && sha256sum -c SHA256SUMS.txt >/dev/null 2>&1 ); then
  printf '  ok    %-22s exit=0  the directory'"'"'s own manifest passes where the record refuses\n' "manifest-disagrees"
  OK=$((OK + 1))
else
  printf '  FAIL  %-22s a self-consistent manifest should pass its own check\n' "manifest-disagrees"
  BAD=$((BAD + 1))
fi

# 4. an absent member - named as absent, and NOT as a hash mismatch
MISSINGDIR=$W/missing
mkdir -p "$MISSINGDIR"; for f in $FILES; do cp "$GOOD/$f" "$MISSINGDIR/$f"; done
rm -f "$MISSINGDIR/xnu_arm_entry.bin"
cell "absent-member"       1 "xnu_arm_entry.bin is ABSENT"        \
  bash "$TOOL" "$MISSINGDIR" --record="$W/fixture-record.txt"

# 5. the right name with the wrong size - refused before any hashing
SHORT=$W/short
mkdir -p "$SHORT"; for f in $FILES; do cp "$GOOD/$f" "$SHORT/$f"; done
head -c 4096 "$GOOD/xnu_arm_entry.bin" > "$SHORT/xnu_arm_entry.bin"
cell "wrong-size"          1 "bytes, the record says"             \
  bash "$TOOL" "$SHORT" --record="$W/fixture-record.txt"

# 6. empty
EMPTY=$W/empty
mkdir -p "$EMPTY"; for f in $FILES; do cp "$GOOD/$f" "$EMPTY/$f"; done
: > "$EMPTY/stage90.bin"
cell "empty-member"        1 "stage90.bin is empty"               \
  bash "$TOOL" "$EMPTY" --record="$W/fixture-record.txt"

# 7. absent / non-directory targets: a fact about the directory, not about the bytes
cell "absent-dir"          1 "does not exist"                     \
  bash "$TOOL" "$W/nope" --record="$W/fixture-record.txt"
cell "not-a-directory"     1 "is not a directory"                 \
  bash "$TOOL" "$GOOD/stage90.bin" --record="$W/fixture-record.txt"

# 8. the record itself
: > "$W/empty-record.txt"
cell "empty-record"        1 "no readable record"                 \
  bash "$TOOL" "$GOOD" --record="$W/empty-record.txt"
cell "absent-record"       1 "no readable record"                 \
  bash "$TOOL" "$GOOD" --record="$W/there-is-no-record-here.txt"
printf '# only a comment\n' > "$W/comment-record.txt"
cell "record-with-no-lines" 1 "carries no file lines"             \
  bash "$TOOL" "$GOOD" --record="$W/comment-record.txt"

# 9. malformed record lines - each refused BY NAME, since an ignored field is a file nobody checked.
# The sed patterns are deliberately unanchored: the fields sit mid-line in `set= x sha256= y` order, and
# an anchored `s/^sha256=/` silently matches nothing - which is a cell that passes by doing nothing, the
# exact failure this battery exists to catch. It caught this one on the first run.
sed 's/ sha256=/ sha265=/' "$W/fixture-record.txt" > "$W/typo-field.txt"
cell "typo-in-field-name"  1 "field this script does not know"    \
  bash "$TOOL" "$GOOD" --record="$W/typo-field.txt"
sed 's/ sha256=\([0-9a-f]\{63\}\)[0-9a-f]/ sha256=\1/' "$W/fixture-record.txt" > "$W/short-hash.txt"
cell "63-hex-sha256"       1 "no usable sha256"                   \
  bash "$TOOL" "$GOOD" --record="$W/short-hash.txt"
sed 's| file=stage90.bin| file=sub/stage90.bin|' "$W/fixture-record.txt" > "$W/path-in-file.txt"
cell "path-in-file-field"  1 "with a path separator"              \
  bash "$TOOL" "$GOOD" --record="$W/path-in-file.txt"
sed 's/ bytes=[0-9]*/ bytes=/' "$W/fixture-record.txt" > "$W/no-bytes.txt"
cell "missing-bytes"       1 "no usable bytes"                    \
  bash "$TOOL" "$GOOD" --record="$W/no-bytes.txt"
sed 's/ file=stage90.bin/ file=/' "$W/fixture-record.txt" > "$W/no-file.txt"
cell "missing-file-field"  1 "has no file="                      \
  bash "$TOOL" "$GOOD" --record="$W/no-file.txt"

# 10. set selection, and one verdict per directory
cell "unknown-set"        1 "no set named 'nosuch'"              \
  bash "$TOOL" "$GOOD" --record="$W/fixture-record.txt" --set=nosuch
cell "two-directories"    1 "more than one directory"            \
  bash "$TOOL" "$GOOD" "$GOOD" --record="$W/fixture-record.txt"
cell "unknown-argument"   1 "unknown argument"                   \
  bash "$TOOL" "$GOOD" --record="$W/fixture-record.txt" --wat=1

# `--help` prints the header, and the phrase asserted is the LAST line of it. That is the whole check:
# the range was a hard-coded `sed -n '2,45p'` plus a `head -24` until step 613, so a header edit moved
# text past the boundary and the help silently stopped mid-list - the 6a/6b table, the absolute-path trap
# and the usage line all dropped, with nothing failing. Asserting the FINAL line is what makes truncation
# visible, and it fails rather than passes if the header ever grows a line the range does not cover.
cell "help-prints-the-whole-header" 1 "Exit: 0 = every file of every requested set matched" \
  bash "$TOOL" --help

# 11. the host-side guard: a PATH that cannot resolve the tools must refuse, and must blame the HOST.
# The links are absolute (via type -P) on purpose: 608's first attempt built them from `command -v` in
# an interactive shell, where the name can resolve to a FUNCTION, so the links were self-referential and
# the refusal blamed the image for a missing `grep`.
BIN=$W/bin
mkdir -p "$BIN"
for t in bash sha256sum stat awk sed grep tr head cut mktemp sort; do
  p=$(type -P "$t") && ln -s "$p" "$BIN/$t"
done
rm -f "$BIN/grep"
NOGREP=$W/nogrep
mkdir -p "$NOGREP"; for f in $FILES; do cp "$GOOD/$f" "$NOGREP/$f"; done
cell "host-missing-a-tool" 1 "this host is missing grep"          \
  env PATH="$BIN" bash "$TOOL" "$NOGREP" --record="$W/fixture-record.txt"

echo
echo "== the record covers what the gate reads =="

# The set is DEFINED as what the gate reads, and **the gate reads in two ways** - so this section derives
# TWO lists and requires the record to cover their union. One list is not the criterion; it was the whole
# of this record's first version, and it was wrong.
#
#   A. the paths the gate NAMES IN ITS OWN TEXT. Both spellings are required: the gate writes eight of
#      the nine `$OUT/name` and one (`xnu_arm_entry.elf`, in a narration path) `out/stage90/name`, so a
#      derivation that greps one spelling returns a shorter list - and a shorter list is what a missing
#      record line looks like. That is how this file's first version lost `stage90.elf`.
#
#   B. the members of THE MANIFEST THE GATE VERIFIES. `preflight_boot_check.sh:139` is
#      `( cd "$OUT" && sha256sum -c SHA256SUMS.txt )`, and `sha256sum -c` opens every path the manifest
#      names. That manifest is itself in A, so B is a property of a file INSIDE the set and not of the
#      gate's text: **no grep of the gate can return these names.** Two of them
#      (`stage90.img`, `stage90_fixture.macho`) are in neither A nor this record's first version, and a
#      revert that omits `stage90.img` makes the restored manifest print `stage90.img: FAILED` - the gate
#      red. The two `manifest-*` cells below reproduce that mechanism directly.
#
# The limit of B as derived here, stated rather than glossed: the fixture's manifest is the one copied
# from the LIVE tree, so this is the live build's member list and a proxy for the recorded manifest's.
# The authoritative check stays *revert, then run the gate*.
#
# **AND ONE MATCH IS NOT A PATH AT ALL, WHICH IS THE THIRD SPELLING THIS DERIVATION HAD TO LEARN - 729.**
# `preflight_boot_check.sh:788` is `[[ -n $_f && -r $OUT/captures/$_f ]]`: the gate JOINS a name it took
# from an argument to `$OUT/captures`, so `captures` is a *directory of archived runs* and the longer
# expression is a per-run file. The first regex stopped at the `/`, and the derived list therefore
# carried a tenth entry - `captures` - that no revert set can hold and no park can contain, so the
# `record-covers-gate` cell printed FAIL about a record that covers everything the gate reads. A
# derivation that reads a PREFIX of a path expression as a member is a claim about the extractor's scope
# and not about the record (m671/m672), and a rehearsal with one permanent FAIL is one whose real
# refusals are unreadable. A match followed by `/` or `$` is now dropped: it is a fragment of a longer
# expression, not a name.
GATESRC=$ROOT/scripts/preflight_boot_check.sh
DERIVED=$W/gate-reads.txt
grep -oE '\$OUT/[A-Za-z0-9_.-]+[$/]?|out/stage90/[A-Za-z0-9_.-]+[$/]?' "$GATESRC" \
  | grep -vE '[/$]$' \
  | sed 's|\$OUT/||; s|out/stage90/||' | sort -u > "$DERIVED"
DERIVED_B=$W/manifest-members.txt
# B comes out of the RECORD, not out of the live tree. The manifest a revert puts back is the record's own
# `SHA256SUMS.txt` member, so its member list is a fact the record can pin - and reading it from
# `out/stage90/SHA256SUMS.txt` instead would read the one file whose contents the next build changes. The
# two are equal today only by coincidence, so a derivation from the live manifest could not tell them
# apart and would start being wrong on the build that adds a member.
grep -E '^set=' "$RECORD" | tr ' ' '\n' | sed -n 's/^manifest_members=//p' | tr ',' '\n' | grep -c . >/dev/null 2>&1 || true
grep -E '^set=' "$RECORD" | tr ' ' '\n' | sed -n 's/^manifest_members=//p' | tr ',' '\n' | grep . | sort -u > "$DERIVED_B"
cat "$DERIVED" "$DERIVED_B" | sort -u > "$W/both.txt"
RECORDED=$W/record-files.txt
grep -E '^set=' "$RECORD" | tr ' ' '\n' | sed -n 's/^file=//p' | sort -u > "$RECORDED"

na=$(wc -l < "$DERIVED"); nb=$(wc -l < "$DERIVED_B"); nall=$(wc -l < "$W/both.txt")
nr=$(wc -l < "$RECORDED")
printf '  info  the gate names %s file(s); the manifest it verifies names %s; union %s; the record names %s\n' \
  "$na" "$nb" "$nall" "$nr"

for part in A B; do
  if [[ $part == A ]]; then src=$DERIVED; label="record-covers-gate"; else src=$DERIVED_B; label="record-covers-manifest"; fi
  if [[ ! -s $src ]]; then
    printf '  FAIL  %-26s nothing was derived for %s - a derivation that returns nothing is not a pass\n' "$label" "$part"
    BAD=$((BAD + 1)); continue
  fi
  MISS=$(comm -23 "$src" "$RECORDED")
  if [[ -n $MISS ]]; then
    printf '  FAIL  %-26s the record does not cover: %s\n' "$label" "$(echo $MISS | tr '\n' ' ')"
    printf '        A revert set missing a file the gate reads leaves the gate red, which is not a revert.\n'
    BAD=$((BAD + 1))
  else
    printf '  ok    %-26s all %s file(s) of %s are in the record\n' "$label" "$(wc -l < "$src")" "$part"
    OK=$((OK + 1))
  fi
done

# The mechanism, reproduced: a directory holding the recorded set with a manifest that names it must pass
# the manifest's own check, and one stale member must turn that check red. The second cell is the defect
# this section exists for - `stage90.img` was in the manifest and not in the record, and this is what it
# did to a revert.
MAN=$W/manifest
mkdir -p "$MAN"; for f in $FILES; do cp "$GOOD/$f" "$MAN/$f"; done
( cd "$MAN" && sha256sum $(printf '%s\n' $FILES | grep -v '^SHA256SUMS.txt$') > SHA256SUMS.txt )
# and a record for it that carries the manifest's member list, which is what makes checks 6a/6b run
mkrekord "$MAN" "$W/manifest-record.txt" || exit 1
sed -i "s|^set=fixture sha256=\(.*\) file=SHA256SUMS.txt |set=fixture sha256=\1 file=SHA256SUMS.txt manifest_members=$(printf '%s\n' $FILES | grep -v '^SHA256SUMS.txt$' | tr '\n' ',' | sed 's/,$//') |" "$W/manifest-record.txt"
grep -q 'manifest_members=' "$W/manifest-record.txt" || { echo "the manifest record carries no manifest_members= - the two cells below would then pass by doing nothing" >&2; exit 1; }
cell "manifest-passes"     0 ""                               \
  bash -c 'cd "$1" && sha256sum -c SHA256SUMS.txt' _ "$MAN"
STALE=$W/manifest-stale
cp -r "$MAN" "$STALE"
printf '\xff' | dd of="$STALE/stage90.img" bs=1 seek=1000000 conv=notrunc status=none
# The cell for the defect this section exists for: the manifest still names its five members, one of them
# is not the recorded bytes, and `sha256sum -c` says so by name. A revert that fails to restore
# `stage90.img` leaves the gate red on exactly this line.
cell "stale-member-turns-it-red" 1 "stage90.img: FAILED"          \
  bash -c 'cd "$1" && sha256sum -c SHA256SUMS.txt' _ "$STALE"

# Check 6b, as a cell: a manifest on disk naming a file the set does not carry. This is the direction
# coverage cannot catch by itself, and the shape a build that adds a sixth output would produce.
OUTSIDE=$W/outside
cp -r "$MAN" "$OUTSIDE"
printf 'not a build output, just a name the set does not carry\n' > "$OUTSIDE/stage90.map"
( cd "$OUTSIDE" && sha256sum $(printf '%s\n' $FILES | grep -v '^SHA256SUMS.txt$') stage90.map > SHA256SUMS.txt )
# The record is regenerated to describe this directory AFTER its manifest was extended, so that the
# refusal that fires is 6b and not an earlier hash mismatch - otherwise the cell would pass on the wrong
# message, or here on no message at all.
mkrekord "$OUTSIDE" "$W/outside-record.txt" || exit 1
cell "target-manifest-names-outside" 1 "names file(s) the set does not" \
  bash "$TOOL" "$OUTSIDE" --record="$W/outside-record.txt"

# Check 6a, as a cell: a record whose manifest_members names a file that is not a file= line of the set.
sed 's/ manifest_members=.*/ manifest_members=stage90-qudt.img/' "$W/manifest-record.txt" > "$W/mm-bad.txt"
cell "manifest-member-not-in-set"   1 "not a file= line of set" \
  bash "$TOOL" "$MAN" --record="$W/mm-bad.txt"

# THE SHRINKAGE DIRECTION, which neither member check covers. A manifest with a member REMOVED is refused
# by check 5 - the manifest is itself a hashed member whose bytes the record pins - while 6a and 6b stay
# silent: 6a reads the record's own `manifest_members=` field, which the shrink does not touch, and 6b
# looks for names the set does NOT carry, of which a shrunk manifest has none. This is the direction the
# record's first version was blind to, and the reason `manifest_members=` and check 5 are complements.
#
# These cells assert SILENCE, and an assertion of silence is the one form of test that a command which
# does nothing passes - the defect this battery has already caught four times. So the run is captured once
# and a preflight requires that it actually refused for the stated reason, that the fixture really shrank,
# and that the output is non-empty, before either "stayed silent" line is allowed to be green.
SHRUNK=$W/shrunk
cp -r "$MAN" "$SHRUNK"
n_before=$(grep -c . "$MAN/SHA256SUMS.txt")
grep -v 'stage90\.img$' "$MAN/SHA256SUMS.txt" > "$SHRUNK/SHA256SUMS.txt"
n_after=$(grep -c . "$SHRUNK/SHA256SUMS.txt")
if [[ $n_after -ne $((n_before - 1)) ]]; then
  printf '  FAIL  %-26s the fixture was not shrunk (%s members before, %s after) - the cells below would\n' \
    "shrunk-fixture" "$n_before" "$n_after"
  printf '        then be asserting silence about a manifest that was never altered.\n'
  BAD=$((BAD + 1))
else
  printf '  ok    %-26s the manifest went from %s member(s) to %s, which is what check 5 has to catch\n' \
    "shrunk-fixture" "$n_before" "$n_after"
  OK=$((OK + 1))
fi
SHRUNK_OUT=$(bash "$TOOL" "$SHRUNK" --record="$W/manifest-record.txt" 2>&1); SHRUNK_RC=$?
if [[ $SHRUNK_RC -ne 1 ]] || ! printf '%s' "$SHRUNK_OUT" | grep -qF -- "bytes, the record says"; then
  printf '  FAIL  %-26s exit=%s without the check-5 size refusal, so the two cells below would pass by\n' \
    "shrunk-refused-by-bytes" "$SHRUNK_RC"
  printf '        saying nothing about a run that said nothing - a silence asserting a silence.\n'
  BAD=$((BAD + 1))
else
  printf '  ok    %-26s exit=%s  bytes, the record says\n' "shrunk-refused-by-bytes" "$SHRUNK_RC"
  OK=$((OK + 1))
fi
for pair in "shrunk-6b-silent:names file(s) the set does not:6b" \
            "shrunk-6a-silent:not a file= line of set:6a"; do
  name=${pair%%:*}; rest=${pair#*:}; phrase=${rest%%:*}; which=${rest##*:}
  if printf '%s' "$SHRUNK_OUT" | grep -qF -- "$phrase"; then
    printf '  FAIL  %-26s %s fired on the shrunk manifest too - the partition in the verifier header is\n' "$name" "$which"
    printf '        then wrong about which check covers the shrinkage direction.\n'
    BAD=$((BAD + 1))
  else
    printf '  ok    %-26s %s stayed silent, as the partition says\n' "$name" "$which"
    OK=$((OK + 1))
  fi
done

echo
if [[ $BAD -eq 0 ]]; then
  echo "  $OK ok, 0 failed"
  echo
  echo "Every refusal fires, names the member or the host it is about, and the honest case passes."
  echo "No device, no build, no fastboot, and the parked set at /tmp/r594/frozen-payload was never read."
  exit 0
fi
echo "  $OK ok, $BAD failed" >&2
exit 1
