#!/usr/bin/env bash
#
# Rehearse `tools/verify_revert_set.sh` with no device, no build and no copy of the parked set.
#
# Why a rehearsal and not a table in a document: a refusal that has never been shown to fire is a claim,
# and this project's record is full of checks that passed because they never ran. Every cell below
# invokes the real tool against a real directory and asserts the exit code AND a phrase of the output,
# so a cell fails loudly if a refusal becomes a silence or starts naming the wrong fault.
#
# The expensive input is real, and it is two files: a genuine park is 27 MB of build output, so the
# fixture is built from the *live* `out/stage90/` - the files the gate reads are all there - and then the
# record is rewritten to describe the copies rather than the originals. That keeps the bytes real (so a
# hash mismatch is a real hash mismatch) without carrying a park in the repository, which is also why the
# fixture directory is a temporary one and is never `/tmp/r594/frozen-payload`.
#
# The cells that matter most point the REAL record at the REAL live tree, which currently holds the
# SLEEPER arm: it must refuse. A verifier that accepted it would be the very defect `revert-set.txt`
# describes - a verdict about a location read as a verdict about a set.
#
# The last cell is the one that would have caught this record's first draft. The set is DEFINED as the
# files the gate reads, so the record must cover that list - and the list is derived from the gate's own
# source at run time rather than trusted from the hand-written one above, which carried eight files while
# the gate read nine.
#
# Usage: ./tools/rehearse_revert_set.sh          (exit 0 = every cell behaved as its own wording promises)

set -uo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
TOOL=$ROOT/tools/verify_revert_set.sh
RECORD=$ROOT/stages/stage90/revert-set.txt
LIVE=$ROOT/out/stage90

[[ -x $TOOL ]] || { echo "no tool at $TOOL" >&2; exit 1; }
[[ -d $LIVE ]] || { echo "no live tree at $LIVE - this rehearsal needs the real build outputs" >&2; exit 1; }

W=$(mktemp -d /tmp/rehearse-revert.XXXXXX) || exit 1
trap 'rm -rf "$W"' EXIT

FILES="SHA256SUMS.txt stage90.bin stage90-build-config.txt stage90.elf stage90-qcdt.img xnu_arm_entry.bin xnu_arm_entry-config.txt xnu_arm_entry.elf xnu_arm_entry-sources.txt"

# The record the cells verify against: the real one, retargeted at the fixture's own bytes.
mkrekord() {   # mkrekord DIR OUT
  local dir=$1 out=$2
  : > "$out"
  echo "# generated by the rehearsal from $dir - the same field set and order as the real record" >> "$out"
  local f
  for f in $FILES; do
    [[ -f $dir/$f ]] || { echo "fixture is missing $f" >&2; return 1; }
    printf 'set=fixture sha256=%s bytes=%s file=%s role=rehearsal\n' \
      "$(sha256sum "$dir/$f" | cut -d' ' -f1)" "$(stat -c%s "$dir/$f")" "$f" >> "$out"
  done
}

# ---- the fixture ---------------------------------------------------------------------------------
GOOD=$W/good
mkdir -p "$GOOD"
for f in $FILES; do cp "$LIVE/$f" "$GOOD/$f"; done
mkrekord "$GOOD" "$W/fixture-record.txt" || exit 1
# The fixture's manifest names the LIVE tree, not the fixture, because that is what the build wrote.
# That is not doctored: it is what every park's manifest does, and the narration cell reads it.

OK=0; BAD=0
cell() {  # cell NAME EXPECTED_EXIT EXPECTED_PHRASE CMD...
  local name=$1 want=$2 phrase=$3; shift 3
  local out rc
  out=$("$@" 2>&1); rc=$?
  if [[ $rc -ne $want ]]; then
    printf '  FAIL  %-22s exit=%s expected %s\n' "$name" "$rc" "$want"
    printf '%s\n' "$out" | sed 's/^/          /' | head -6
    BAD=$((BAD + 1)); return
  fi
  if [[ -n $phrase ]] && ! printf '%s' "$out" | grep -qF -- "$phrase"; then
    printf '  FAIL  %-22s exit=%s but said nothing about: %s\n' "$name" "$rc" "$phrase"
    printf '%s\n' "$out" | sed 's/^/          /' | head -6
    BAD=$((BAD + 1)); return
  fi
  printf '  ok    %-22s exit=%s  %s\n' "$name" "$rc" "$phrase"
  OK=$((OK + 1))
}

echo
echo "== the revert-set verifier, rehearsed with no device =="
echo "   tool:   $TOOL"
echo "   record: the real one, retargeted at a real fixture built from $LIVE"
echo "   fixture $GOOD  (the files the gate reads, copied from $LIVE; ${W} is removed at exit)"
echo

# 1. the honest case: the fixture's own bytes against a record that describes them
cell "good-set"            0 "VERIFIED:"                        \
  bash "$TOOL" "$GOOD" --record="$W/fixture-record.txt"
cell "good-set-a-set-name" 0 "set fixture in"                   \
  bash "$TOOL" "$GOOD" --record="$W/fixture-record.txt" --set=fixture

# 2. the cells this rehearsal exists for: a record describing ONE set, pointed at a directory holding
# ANOTHER. This uses the REAL record and the REAL live tree, with no copy in between: `revert-set.txt`
# describes the parked frozen 574 bytes, and `out/stage90/` currently holds the SLEEPER arm. A verifier
# that accepted it would be the defect `revert-set.txt` describes - a verdict about a directory read as
# a verdict about the set, which is what `sha256sum -c` does to every park.
cell "live-tree-vs-record" 1 "stage90-qcdt.img hashes to"        \
  bash "$TOOL" "$LIVE"
cell "live-tree-names-the-dir" 1 "in $LIVE"                       \
  bash "$TOOL" "$LIVE"

# 3. a one-byte edit, past the header so the file still parses as an image
BADHASH=$W/badhash
mkdir -p "$BADHASH"; for f in $FILES; do cp "$GOOD/$f" "$BADHASH/$f"; done
printf '\xff' | dd of="$BADHASH/stage90-qcdt.img" bs=1 seek=1000000 conv=notrunc status=none
cell "one-byte-edited"     1 "stage90-qcdt.img hashes to"        \
  bash "$TOOL" "$BADHASH" --record="$W/fixture-record.txt"

# 3b. the same directory, but with its OWN manifest regenerated to describe the edited bytes - so the
# manifest is self-consistent and the parked set is still not the recorded one. The tool must refuse
# anyway, because it hashes from the record and never from a manifest it finds in the target. The two
# readings are shown side by side, because the whole point of the record is that they can disagree.
SELFCON=$W/self-consistent
cp -r "$BADHASH" "$SELFCON"
# The manifest must not list itself: the redirect truncates the file before `sha256sum` opens it, so a
# self-referential line records the hash of an empty file and every check against that manifest fails on
# the manifest rather than on the bytes. That is what the first run of this cell did.
( cd "$SELFCON" && sha256sum $(printf '%s\n' $FILES | grep -v '^SHA256SUMS.txt$') > SHA256SUMS.txt )
cell "self-consistent-manifest" 1 "stage90-qcdt.img hashes to"   \
  bash "$TOOL" "$SELFCON" --record="$W/fixture-record.txt"
if ( cd "$SELFCON" && sha256sum -c SHA256SUMS.txt >/dev/null 2>&1 ); then
  printf '  ok    %-22s exit=0  the directory'"'"'s own manifest passes where the record refuses\n' "manifest-disagrees"
  OK=$((OK + 1))
else
  printf '  FAIL  %-22s a self-consistent manifest should pass its own check\n' "manifest-disagrees"
  BAD=$((BAD + 1))
fi

# 4. an absent member - named as absent, and NOT as a hash mismatch
MISSINGDIR=$W/missing
mkdir -p "$MISSINGDIR"; for f in $FILES; do cp "$GOOD/$f" "$MISSINGDIR/$f"; done
rm -f "$MISSINGDIR/xnu_arm_entry.bin"
cell "absent-member"       1 "xnu_arm_entry.bin is ABSENT"        \
  bash "$TOOL" "$MISSINGDIR" --record="$W/fixture-record.txt"

# 5. the right name with the wrong size - refused before any hashing
SHORT=$W/short
mkdir -p "$SHORT"; for f in $FILES; do cp "$GOOD/$f" "$SHORT/$f"; done
head -c 4096 "$GOOD/xnu_arm_entry.bin" > "$SHORT/xnu_arm_entry.bin"
cell "wrong-size"          1 "bytes, the record says"             \
  bash "$TOOL" "$SHORT" --record="$W/fixture-record.txt"

# 6. empty
EMPTY=$W/empty
mkdir -p "$EMPTY"; for f in $FILES; do cp "$GOOD/$f" "$EMPTY/$f"; done
: > "$EMPTY/stage90.bin"
cell "empty-member"        1 "stage90.bin is empty"               \
  bash "$TOOL" "$EMPTY" --record="$W/fixture-record.txt"

# 7. absent / non-directory targets: a fact about the directory, not about the bytes
cell "absent-dir"          1 "does not exist"                     \
  bash "$TOOL" "$W/nope" --record="$W/fixture-record.txt"
cell "not-a-directory"     1 "is not a directory"                 \
  bash "$TOOL" "$GOOD/stage90.bin" --record="$W/fixture-record.txt"

# 8. the record itself
: > "$W/empty-record.txt"
cell "empty-record"        1 "no readable record"                 \
  bash "$TOOL" "$GOOD" --record="$W/empty-record.txt"
cell "absent-record"       1 "no readable record"                 \
  bash "$TOOL" "$GOOD" --record="$W/there-is-no-record-here.txt"
printf '# only a comment\n' > "$W/comment-record.txt"
cell "record-with-no-lines" 1 "carries no file lines"             \
  bash "$TOOL" "$GOOD" --record="$W/comment-record.txt"

# 9. malformed record lines - each refused BY NAME, since an ignored field is a file nobody checked.
# The sed patterns are deliberately unanchored: the fields sit mid-line in `set= x sha256= y` order, and
# an anchored `s/^sha256=/` silently matches nothing - which is a cell that passes by doing nothing, the
# exact failure this battery exists to catch. It caught this one on the first run.
sed 's/ sha256=/ sha265=/' "$W/fixture-record.txt" > "$W/typo-field.txt"
cell "typo-in-field-name"  1 "field this script does not know"    \
  bash "$TOOL" "$GOOD" --record="$W/typo-field.txt"
sed 's/ sha256=\([0-9a-f]\{63\}\)[0-9a-f]/ sha256=\1/' "$W/fixture-record.txt" > "$W/short-hash.txt"
cell "63-hex-sha256"       1 "no usable sha256"                   \
  bash "$TOOL" "$GOOD" --record="$W/short-hash.txt"
sed 's| file=stage90.bin| file=sub/stage90.bin|' "$W/fixture-record.txt" > "$W/path-in-file.txt"
cell "path-in-file-field"  1 "with a path separator"              \
  bash "$TOOL" "$GOOD" --record="$W/path-in-file.txt"
sed 's/ bytes=[0-9]*/ bytes=/' "$W/fixture-record.txt" > "$W/no-bytes.txt"
cell "missing-bytes"       1 "no usable bytes"                    \
  bash "$TOOL" "$GOOD" --record="$W/no-bytes.txt"
sed 's/ file=stage90.bin/ file=/' "$W/fixture-record.txt" > "$W/no-file.txt"
cell "missing-file-field"  1 "has no file="                      \
  bash "$TOOL" "$GOOD" --record="$W/no-file.txt"

# 10. set selection, and one verdict per directory
cell "unknown-set"        1 "no set named 'nosuch'"              \
  bash "$TOOL" "$GOOD" --record="$W/fixture-record.txt" --set=nosuch
cell "two-directories"    1 "more than one directory"            \
  bash "$TOOL" "$GOOD" "$GOOD" --record="$W/fixture-record.txt"
cell "unknown-argument"   1 "unknown argument"                   \
  bash "$TOOL" "$GOOD" --record="$W/fixture-record.txt" --wat=1

# 11. the host-side guard: a PATH that cannot resolve the tools must refuse, and must blame the HOST.
# The links are absolute (via type -P) on purpose: 608's first attempt built them from `command -v` in
# an interactive shell, where the name can resolve to a FUNCTION, so the links were self-referential and
# the refusal blamed the image for a missing `grep`.
BIN=$W/bin
mkdir -p "$BIN"
for t in bash sha256sum stat awk sed grep tr head cut mktemp sort; do
  p=$(type -P "$t") && ln -s "$p" "$BIN/$t"
done
rm -f "$BIN/grep"
NOGREP=$W/nogrep
mkdir -p "$NOGREP"; for f in $FILES; do cp "$GOOD/$f" "$NOGREP/$f"; done
cell "host-missing-a-tool" 1 "this host is missing grep"          \
  env PATH="$BIN" bash "$TOOL" "$NOGREP" --record="$W/fixture-record.txt"

echo
echo "== the record covers what the gate reads =="

# The set is DEFINED as "the files the gate reads", so the record has to cover that list - and the list
# is derived here at run time rather than trusted from the one at the top of this file, because that one
# was hand-written and carried eight files while the gate read nine. A hand-written list of what a
# program reads is a claim about that program; this is the check on it.
#
# BOTH spellings are required. The gate names eight of the nine through `$OUT/name` and one through
# `out/stage90/name`, so a derivation that greps for one spelling silently returns a shorter list - and a
# shorter list is exactly what a missing record line looks like.
GATESRC=$ROOT/stages/stage90/preflight_boot_check.sh
DERIVED=$W/gate-reads.txt
grep -oE '\$OUT/[A-Za-z0-9_.-]+|out/stage90/[A-Za-z0-9_.-]+' "$GATESRC" \
  | sed 's|\$OUT/||; s|out/stage90/||' | sort -u > "$DERIVED"
RECORDED=$W/record-files.txt
grep -E '^set=' "$RECORD" | tr ' ' '\n' | sed -n 's/^file=//p' | sort -u > "$RECORDED"

nd=$(wc -l < "$DERIVED"); nr=$(wc -l < "$RECORDED")
printf '  info  the gate reads %s file(s); the record names %s\n' "$nd" "$nr"

UNCOVERED=$(comm -23 "$DERIVED" "$RECORDED")
if [[ -n $UNCOVERED ]]; then
  printf '  FAIL  %-22s the record does not cover: %s\n' "record-covers-gate" "$(echo $UNCOVERED | tr '\n' ' ')"
  printf '        A revert set missing a file the gate reads leaves the gate red, which is not a revert.\n'
  BAD=$((BAD + 1))
else
  printf '  ok    %-22s all %s file(s) the gate reads are in the record\n' "record-covers-gate" "$nd"
  OK=$((OK + 1))
fi
EXTRA=$(comm -13 "$DERIVED" "$RECORDED")
if [[ -n $EXTRA ]]; then
  printf '  info  the record also names file(s) the gate does not read: %s\n' "$(echo $EXTRA | tr '\n' ' ')"
fi

echo
if [[ $BAD -eq 0 ]]; then
  echo "  $OK ok, 0 failed"
  echo
  echo "Every refusal fires, names the member or the host it is about, and the honest case passes."
  echo "No device, no build, no fastboot, and the parked set at /tmp/r594/frozen-payload was never read."
  exit 0
fi
echo "  $OK ok, $BAD failed" >&2
exit 1
