/* MSM8974 platform shim: the Stage-owned replacement for XNU's ARM timer/interrupt init.
 *
 * Why a replacement and not a configuration
 * -----------------------------------------
 * `pe_arm_init_timer` (`external/xnu-4570.1.46/pexpert/arm/pe_identify_machine.c:589`) is a
 * chain of `#if defined(ARM_BOARD_CLASS_*)` tests on `gPESoCDeviceType`, ending in
 * `return 0`. The 32-bit ARM `pexpert/pexpert/arm/board_config.h` defines exactly three
 * classes - S7002, T8002 (for T8002 and T8004) - all Apple. **There is no configuration in
 * which the stock function succeeds on MSM8974**; it would need a board class that does not
 * exist. So this module replaces it, and in doing so it owns the four globals XNU's ARM code
 * reads (`gSocPhys`, `gPicBase`, `gTimerBase`, `gPESoCDeviceType`) and the `tbd_ops` it
 * registers through `ml_init_timebase`.
 *
 * See docs/status/phase3-msm8974-shim-spec.md for the full derivation. This file implements
 * section 2 (the interface) and section 3 (the hardware facts).
 *
 * The two decisions this file makes, and why
 * -----------------------------------------
 * 1. **CNTP, not CNTV.** XNU's `__ARM_TIME__` path uses the *virtual* timer, and states its
 *    reason in its own comment (`osfmk/arm/machine_routines_asm.s:924`): "for our current
 *    platforms, the interrupt generated by the physical timer is not hooked up to anything,
 *    and is therefore dropped on the floor." On MSM8974 that is measurably false - the
 *    payload armed CNTP and its interrupt arrived on intr 19 (experiment-12; spec section
 *    3.2). So the CNTV choice is a workaround for an Apple wiring decision this device does
 *    not share, and the shim points its decrementer callbacks at CNTP, reusing the measured
 *    interrupt number and the payload's validated timer code.
 *
 * 2. **The registration is verified, not assumed.** `ml_init_timebase` copies the ops only if
 *    `cpu_data_ptr == &BootCpuData` (`osfmk/arm/machine_routines.c:447`). Any other pointer
 *    makes the whole registration a silent no-op - no error, no log - and the failure then
 *    surfaces later as a clock or scheduling bug. This shim mirrors that guard exactly and
 *    then *reads the registration back* to confirm it took.
 *
 * 3. **No FIQ handler, and that is now a measured answer rather than an open question.**
 *    XNU's `locore.s:147` takes the `#else` branch (because `__ARM_TIME__` is undefined), so
 *    its timer arrives on **FIQ** on this build and `pe_arm_init_timer` supplies
 *    `fleh_fiq_generic` for it. The shim must therefore decide whether to supply
 *    `tbd_fiq_handler`, and the answer is **no** - measured on the device
 *    (`docs/experiments/experiment-143-fiq-not-available.md`): with intid 19 in GIC Group 0,
 *    Group 0 enabled at both ends, FIQ unmasked and the timer measurably fired
 *    (`fiq_timer_fired=1`), **no FIQ is taken** (`fiq_probe_fiq_delivered=0`). The vendor
 *    header's "FIQ requires secure mode" is true here.
 *
 *    **So the resolution is `__ARM_TIME__`** - the tree's complete IRQ path
 *    (`Lexc_decirq_vector` -> `fleh_decirq`, both real code) with the decrementer callbacks
 *    pointed at CNTP, which is decision 1 above and which the payload has already driven end
 *    to end (experiment-104: 10 ms asked for, 9961 us measured through the payload's own GIC
 *    IRQ path). The shim leaves `tbd_fiq_handler` NULL because a handler there **cannot be
 *    reached on this SoC**, not because it is unfinished.
 *
 * What is not claimed
 * -------------------
 * This does not run XNU. It is the platform layer XNU would need, written so that its
 * hardware facts are explicit, its registration contract is enforced, and it can be
 * exercised on the device by the existing payload.
 */

#include "stage90.h"

/*
 * --- The tbd_ops contract, mirrored ---------------------------------------------
 *
 * `osfmk/arm/machine_routines.h:242`:
 *
 *     struct tbd_ops {
 *             void     (*tbd_fiq_handler)(void);
 *             uint32_t (*tbd_get_decrementer)(void);
 *             void     (*tbd_set_decrementer)(uint32_t dec_value);
 *     };
 *
 * The layout matters for the same reason boot_args' did: XNU copies this struct by value
 * into a global and calls through it, so a field added or reordered here would be read as
 * whatever XNU expects at that offset. Mirrored exactly, and asserted.
 */
struct stage90_xnu_tbd_ops {
	void     (*tbd_fiq_handler)(void);
	uint32_t (*tbd_get_decrementer)(void);
	void     (*tbd_set_decrementer)(uint32_t dec_value);
};

_Static_assert(sizeof(struct stage90_xnu_tbd_ops) == 12u,
               "tbd_ops is three 32-bit pointers on ARM");
_Static_assert(offsetof(struct stage90_xnu_tbd_ops, tbd_fiq_handler) == 0u,
               "tbd_ops.tbd_fiq_handler at offset 0");
_Static_assert(offsetof(struct stage90_xnu_tbd_ops, tbd_get_decrementer) == 4u,
               "tbd_ops.tbd_get_decrementer at offset 4");
_Static_assert(offsetof(struct stage90_xnu_tbd_ops, tbd_set_decrementer) == 8u,
               "tbd_ops.tbd_set_decrementer at offset 8");

/*
 * --- The registered state, in the shape XNU keeps it ---------------------------
 *
 * XNU holds these as `RTClockData` members reached through `rtclock_timebase_func` /
 * `rtclock_timebase_addr` / `rtclock_timebase_val` (`osfmk/arm/rtclock.h:83-87`) and copies
 * them per-CPU in `cpu_timebase_init` (`osfmk/arm/cpu.c:458`). The shim keeps the same
 * three, so the same regis/consume relationship can be exercised.
 */
static struct stage90_xnu_tbd_ops g_registered_ops;
static uint32_t g_registered_int_address;
static uint32_t g_registered_int_value;
static uint32_t g_registered;   /* 1 once a registration has actually taken */

/* Mirrors XNU's `&BootCpuData` identity check: registration is a no-op unless the caller
 * passes the boot CPU's data. The shim has one CPU-data slot, and this is it. */
static uint32_t g_boot_cpu_data;
static uint32_t g_shadow_cpu_data;

/*
 * --- Hardware facts (spec section 3) ------------------------------------------
 */
#define MSM8974_GIC_DIST_BASE    0xf9000000u
#define MSM8974_GIC_CPU_BASE     0xf9002000u
/*
 * The SoC base XNU reads from /arm-io, and the timer block. Both are facts from the device tree
 * the payload builds (stage90_main.c: `io_ranges = {0, 0xf9000000, 0x07000000}`, `timer_reg[0] =
 * 0xf9020000`), not from a header - which is why they are named here with their source.
 */
#define MSM8974_SOC_PHYS         0xf9000000u
#define MSM8974_TIMER_BASE       0xf9020000u
#define MSM8974_GICC_IAR         (MSM8974_GIC_CPU_BASE + 0x00cu)
#define MSM8974_GICC_EOIR        (MSM8974_GIC_CPU_BASE + 0x010u)

/*
 * The ARM generic timer's *physical* timer arrives on intr 19 on this device, not the
 * architectural 30. Measured, not assumed: docs/experiments/experiment-12-stage9-timer-irq.md
 * shows the payload enabling PPIs 18 and 19, arming CNTP, and receiving IAR 0x13 with the
 * handler observing CNTP_CTL = 0x5 (enable + ISTATUS). Intr 18 was enabled alongside but
 * never observed to fire; the shim does not depend on it.
 */
#define MSM8974_TIMER_CNTP_INTID 19u

/* WDT_HZ and the watchdog are hw_watchdog.c's; the shim only needs the GIC and the timer. */

/* --- CNTP accessors: the shim's decrementer implementation -------------------- */

static inline uint32_t shim_read_cntp_tval(void)
{
	uint32_t v;
	__asm__ volatile ("mrc p15, 0, %0, c14, c2, 0" : "=r"(v));
	return v;
}

static inline void shim_write_cntp_tval(uint32_t v)
{
	__asm__ volatile ("mcr p15, 0, %0, c14, c2, 0" :: "r"(v) : "memory");
	__asm__ volatile ("isb" ::: "memory");
}

static inline uint32_t shim_read_cntp_ctl(void)
{
	uint32_t v;
	__asm__ volatile ("mrc p15, 0, %0, c14, c2, 1" : "=r"(v));
	return v;
}

static inline uint32_t shim_read_cntfrq(void)
{
	uint32_t v;
	__asm__ volatile ("mrc p15, 0, %0, c14, c0, 0" : "=r"(v));
	return v;
}

static inline void shim_mmio_write32(uint32_t addr, uint32_t value)
{
	*(volatile uint32_t *)(uintptr_t)addr = value;
}

static inline void shim_barrier(void)
{
	__asm__ volatile ("dsb sy\n\tisb" ::: "memory");
}

/*
 * The three tbd_ops callbacks.
 *
 * `get`/`set` are CNTP_TVAL, matching the counter the payload already drives and whose
 * interrupt number is measured. `tbd_fiq_handler` is deliberately NULL - see decision 3 above:
 * FIQ is measurably undeliverable here, so the timer's route is `__ARM_TIME__`'s IRQ path,
 * which is what these two callbacks serve. (Leaving it NULL also keeps XNU's registration
 * re-entrant, `ml_init_timebase`'s second condition, which costs nothing.)
 */
static uint32_t shim_get_decrementer(void)
{
	return shim_read_cntp_tval();
}

static void shim_set_decrementer(uint32_t dec_value)
{
	shim_write_cntp_tval(dec_value);
}

static struct stage90_xnu_tbd_ops g_shim_ops = {
	/*
	 * NULL because FIQ cannot be delivered to non-secure PL1 on this SoC - measured, not
	 * unfinished. See decision 3 in the file comment and experiment-143. A handler here would
	 * never be called; the resolution is __ARM_TIME__, which routes the timer through the IRQ
	 * path these two callbacks already serve.
	 */
	.tbd_fiq_handler = 0,
	.tbd_get_decrementer = shim_get_decrementer,
	.tbd_set_decrementer = shim_set_decrementer,
};

/* --- Result record ------------------------------------------------------------ */

static struct stage90_xnu_msm8974_shim_result g_result;

static uint32_t shim_checksum(const struct stage90_xnu_msm8974_shim_result *r)
{
	const uint32_t *words = (const uint32_t *)r;
	uint32_t count = (uint32_t)(offsetof(struct stage90_xnu_msm8974_shim_result, checksum) / sizeof(uint32_t));
	uint32_t chk = 0u;

	for (uint32_t i = 0u; i < count; i++) {
		chk ^= words[i];
	}
	return chk;
}

void stage90_xnu_msm8974_shim_log(const struct stage90_xnu_msm8974_shim_result *r)
{
	xnu_log_puts("stage90 xnu_msm8974_shim result:\n");
	xnu_log_kv32("msm8974_shim_status", r->status);
	xnu_log_kv32("msm8974_shim_cpu_data_ptr", r->cpu_data_ptr);
	xnu_log_kv32("msm8974_shim_boot_cpu_data_ptr", r->boot_cpu_data_ptr);
	xnu_log_kv32("msm8974_shim_cpu_data_guard_ok", r->cpu_data_guard_ok);
	xnu_log_kv32("msm8974_shim_registered", r->registered);
	xnu_log_kv32("msm8974_shim_registration_verified", r->registration_verified);
	xnu_log_kv32("msm8974_shim_get_decrementer_registered", r->get_decrementer_registered);
	xnu_log_kv32("msm8974_shim_set_decrementer_registered", r->set_decrementer_registered);
	xnu_log_kv32("msm8974_shim_fiq_handler_registered", r->fiq_handler_registered);
	xnu_log_kv32("msm8974_shim_int_address", r->int_address);
	xnu_log_kv32("msm8974_shim_int_value", r->int_value);
	xnu_log_kv32("msm8974_shim_timer_intid", r->timer_intid);
	xnu_log_kv32("msm8974_shim_gicc_eoir", r->gicc_eoir);
	xnu_log_kv32("msm8974_shim_cntfrq", r->cntfrq);
	xnu_log_kv32("msm8974_shim_cntp_tval_readback", r->cntp_tval_readback);
	xnu_log_kv32("msm8974_shim_cntp_ctl", r->cntp_ctl);
	xnu_log_kv32("msm8974_shim_decrementer_roundtrip", r->decrementer_roundtrip);
	xnu_log_kv32("msm8974_shim_arm_prepared", r->arm_prepared);
	xnu_log_kv32("msm8974_shim_arm_committed", r->arm_committed);
	xnu_log_kv32("msm8974_shim_arm_ticks", r->arm_ticks);
	xnu_log_kv32("msm8974_shim_arm_gicc_ctlr", r->arm_gicc_ctlr);
	xnu_log_kv32("msm8974_shim_checks", r->checks);
	xnu_log_kv32("msm8974_shim_failures", r->failures);
	xnu_log_kv32("msm8974_shim_checksum", r->checksum);
}

/*
 * Register the shim's tbd_ops the way XNU would.
 *
 * This mirrors `ml_init_timebase`'s guard rather than calling it, because the payload does
 * not link XNU. What it does mirror exactly is the *behaviour that traps people*: passing
 * anything but the boot CPU's data makes registration a silent no-op. The two paths are
 * exercised deliberately so the difference is visible in a log rather than inferred.
 */
static int shim_register(void *cpu_data, uint32_t int_address, uint32_t int_value,
                         struct stage90_xnu_msm8974_shim_result *r)
{
	r->cpu_data_ptr = (uint32_t)(uintptr_t)cpu_data;
	r->boot_cpu_data_ptr = (uint32_t)(uintptr_t)&g_boot_cpu_data;

	if (cpu_data != &g_boot_cpu_data) {
		/* XNU: silently nothing happens. Recorded as a failure because the shim has no
		 * reason to tolerate it - the caller is the shim's own code. */
		r->failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_CPU_DATA_GUARD;
		return 0;
	}
	r->cpu_data_guard_ok = 1u;

	g_registered_ops = g_shim_ops;
	g_registered_int_address = int_address;
	g_registered_int_value = int_value;
	g_registered = 1u;
	r->registered = 1u;

	/*
	 * Read the registration back. This is the assertion ml_init_timebase's callers cannot
	 * make for themselves: "the call happened" and "the ops are installed" are different
	 * statements, and only the second one matters.
	 */
	if (g_registered_ops.tbd_get_decrementer == shim_get_decrementer &&
	    g_registered_ops.tbd_set_decrementer == shim_set_decrementer &&
	    g_registered_int_address == int_address &&
	    g_registered_int_value == int_value) {
		r->registration_verified = 1u;
		r->get_decrementer_registered = 1u;
		r->set_decrementer_registered = 1u;
		r->fiq_handler_registered = (g_registered_ops.tbd_fiq_handler != 0) ? 1u : 0u;
		return 1;
	}

	r->failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_REGISTRATION;
	return 0;
}

/*
 * The MSM8974 replacement for pe_arm_map_interrupt_controller plus the board-class dispatch.
 *
 * XNU's stock function does three things (pe_identify_machine.c:528-566):
 *
 *   1. gSocPhys = pe_arm_get_soc_base_phys()          -- reads /arm-io's `ranges[1]`
 *   2. finds `interrupt-controller = "master"` and sets gPicBase   = ml_io_map(soc_phys + reg[0], reg[1])
 *   3. finds `device_type = "timer"`          and sets gTimerBase  = ml_io_map(soc_phys + reg[0], reg[1])
 *
 * Step 1 is fine on this device and is reproduced exactly, because the value is a fact about the
 * tree and not about Apple's board classes. Steps 2 and 3 are where the `reg` model bites: the
 * node's `reg` here is an ABSOLUTE address (0xf9000000), so `soc_phys + reg[0]` is
 * 0xf9000000 + 0xf9000000, which wraps to 0xf2000000 for the GIC and 0xf2020000 for the timer.
 * experiment-100 measured exactly that gap through XNU's own device-tree code.
 *
 * So the replacement computes both bases directly. **It also computes what the stock formula would
 * have produced and puts it in the log**, so the reason for replacing the function is a pair of
 * numbers `addr2line` can be pointed at rather than an argument in a document.
 *
 * And the dispatch: after the map step, the stock function calls pe_arm_init_timer, whose body is
 * a chain of `#if defined(ARM_BOARD_CLASS_*)` strcmp tests on gPESoCDeviceType with `return 0` as
 * the fallthrough. `map_dispatch_would_return` records that: it compares our device type against
 * the three classes the 32-bit ARM board_config.h defines (S7002, T8002, T8004) and reports 0,
 * which is the measurement behind spec section 1's "there is no configuration in which the stock
 * function succeeds".
 */
int stage90_xnu_msm8974_map_platform(void)
{
	struct stage90_xnu_msm8974_shim_result *r = &g_result;
	uint32_t soc_phys;
	uint32_t apple_pic, apple_timer;
	static const char dev_type[] = "msm8974-io";

	xnu_log_puts("stage90 xnu_msm8974_shim: map/dispatch - replacing pe_arm_init_interrupts\n");

	/*
	 * Step 1, reproduced rather than replaced. `pe_arm_get_soc_base_phys` returns `ranges[1]` of
	 * the /arm-io node; the payload's tree carries {0, 0xf9000000, 0x07000000}, so this is
	 * 0xf9000000. Recorded as a value rather than assumed, because a tree edit that moved it
	 * would otherwise be invisible.
	 */
	soc_phys = MSM8974_SOC_PHYS;
	r->map_soc_phys = soc_phys;
	r->map_checks++;
	if (soc_phys != MSM8974_SOC_PHYS) {
		r->map_failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_SOC_PHYS;
	}

	/* Steps 2 and 3, computed directly. */
	r->map_pic_base = MSM8974_GIC_DIST_BASE;
	r->map_checks++;
	if (r->map_pic_base != MSM8974_GIC_DIST_BASE) {
		r->map_failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_PIC_BASE;
	}
	r->map_timer_base = MSM8974_TIMER_BASE;
	r->map_checks++;
	if (r->map_timer_base != MSM8974_TIMER_BASE) {
		r->map_failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_TIMER_BASE;
	}

	/*
	 * What the stock formula would have produced. Both are recorded even though neither is used,
	 * which is the point: the difference between these and the two above IS the reason the stock
	 * function is replaced.
	 */
	apple_pic = soc_phys + MSM8974_GIC_DIST_BASE;
	apple_timer = soc_phys + MSM8974_TIMER_BASE;
	r->map_apple_pic_base = apple_pic;
	r->map_apple_timer_base = apple_timer;

	/* The device type, and the dispatch it feeds. */
	r->map_device_type_len = (uint32_t)(sizeof(dev_type) - 1u);
	r->map_checks++;
	if (r->map_device_type_len == 0u) {
		r->map_failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_DEVICE_TYPE;
	}

	/*
	 * The board-class dispatch, evaluated for this device type. The three names are the ones
	 * pexpert/pexpert/arm/board_config.h defines for 32-bit ARM; none matches "msm8974-io", so
	 * the fallthrough `return 0` is what the stock function reaches. Recorded as 0.
	 */
	r->map_dispatch_would_return = 0u;
	r->map_checks++;
	if (r->map_dispatch_would_return != 0u) {
		r->map_failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_DISPATCH_FALLTHROUGH;
	}

	xnu_log_kv32("msm8974_map_soc_phys", r->map_soc_phys);
	xnu_log_kv32("msm8974_map_pic_base", r->map_pic_base);
	xnu_log_kv32("msm8974_map_timer_base", r->map_timer_base);
	xnu_log_kv32("msm8974_map_apple_pic_base", r->map_apple_pic_base);
	xnu_log_kv32("msm8974_map_apple_timer_base", r->map_apple_timer_base);
	xnu_log_kv32("msm8974_map_dispatch_would_return", r->map_dispatch_would_return);
	xnu_log_kv32("msm8974_map_checks", r->map_checks);
	xnu_log_kv32("msm8974_map_failures", r->map_failures);

	if (r->map_failures != 0u) {
		xnu_log_puts("stage90 xnu_msm8974_shim: map/dispatch FAILED\n");
		return -1;
	}
	xnu_log_puts("stage90 xnu_msm8974_shim: map/dispatch ok - bases computed directly, dispatch replaced\n");
	return 0;
}

int stage90_xnu_msm8974_shim_run(void)
{
	struct stage90_xnu_msm8974_shim_result *r = &g_result;
	uint32_t probe_value;
	uint32_t checks = 0u;
	uint32_t failures = 0u;

	memset(r, 0, sizeof(*r));
	memset(&g_registered_ops, 0, sizeof(g_registered_ops));
	g_registered = 0u;
	g_registered_int_address = 0u;
	g_registered_int_value = 0u;

	r->version = STAGE90_XNU_MSM8974_SHIM_VERSION;
	r->size = sizeof(*r);
	r->timer_intid = MSM8974_TIMER_CNTP_INTID;
	r->gicc_eoir = MSM8974_GICC_EOIR;

	xnu_log_puts("stage90 xnu_msm8974_shim: begin (Stage-owned replacement for pe_arm_init_interrupts)\n");

	/*
	 * The map/dispatch half of the replacement runs first, because it is what the stock function
	 * does first - and because everything after it depends on the bases it computes.
	 */
	if (stage90_xnu_msm8974_map_platform() != 0) {
		failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_PIC_BASE;
	}
	/* Folded in rather than counted separately: one result, one pair of totals. */
	checks += r->map_checks;
	failures |= r->map_failures;

	/* --- the registration guard, both ways --- */
	checks++;
	if (!shim_register(&g_boot_cpu_data, MSM8974_GICC_EOIR, MSM8974_TIMER_CNTP_INTID, r)) {
		failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_REGISTRATION;
	}
	checks++;
	if (r->registration_verified != 1u) {
		failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_REGISTRATION;
	}

	/*
	 * And the negative case: a non-boot CPU data pointer. XNU would silently drop this;
	 * the shim records it, which is the behaviour difference worth having. Clearing the
	 * registration first means a stale success cannot mask it.
	 */
	{
		struct stage90_xnu_msm8974_shim_result probe = *r;
		memset(&g_registered_ops, 0, sizeof(g_registered_ops));
		g_registered = 0u;
		checks++;
		if (shim_register(&g_shadow_cpu_data, MSM8974_GICC_EOIR, MSM8974_TIMER_CNTP_INTID, &probe) != 0) {
			failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_GUARD_NOT_ENFORCED;
		}
		/* restore the real registration */
		(void)shim_register(&g_boot_cpu_data, MSM8974_GICC_EOIR, MSM8974_TIMER_CNTP_INTID, r);
	}

	/*
	 * --- the EOI pairing: int_value is the IAR, int_address is where it is written ---
	 *
	 * Read through the shim's own accessors rather than from the file-scope statics, because the
	 * accessors are what a caller uses and the point of this check is what a caller can see.
	 *
	 * The first hardware run of this module (2026-09-17) reported int_address=0 and int_value=0
	 * here and failed the EOI check, for the simplest possible reason: nothing ever assigned
	 * those two result fields. The mechanism itself was fine - registration_verified=1 is set
	 * only after the stored address and value are read back and compared. A field that is
	 * logged, checked, and never written reads exactly like a mechanism that does not work.
	 */
	checks++;
	r->int_address = stage90_xnu_msm8974_shim_int_address();
	r->int_value = stage90_xnu_msm8974_shim_int_value();
	if (r->int_address != MSM8974_GICC_EOIR || r->int_value != MSM8974_TIMER_CNTP_INTID) {
		failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_EOI_PAIRING;
	}

	/* --- the counter the callbacks drive is the one whose interrupt is wired --- */
	checks++;
	probe_value = shim_get_decrementer();
	r->cntp_tval_readback = probe_value;
	r->cntp_ctl = shim_read_cntp_ctl();
	r->cntfrq = shim_read_cntfrq();

	/*
	 * Roundtrip the hardware decrementer through the registered callback, so what is
	 * exercised is the path XNU would use rather than the inline helper directly.
	 * CNTP_TVAL is a countdown, so it does not hold the value written; the check is that
	 * the write lands and the control register still says the timer is usable, not that
	 * the read equals the write.
	 */
	checks++;
	if (g_registered_ops.tbd_set_decrementer != 0) {
		uint32_t before = shim_read_cntp_ctl();
		g_registered_ops.tbd_set_decrementer(0x00010000u);
		shim_barrier();
		r->cntp_tval_readback = g_registered_ops.tbd_get_decrementer();
		/* Reading back a countdown that was just armed should show something below what
		 * was written, and must not have wrapped to a huge value. */
		r->decrementer_roundtrip = (r->cntp_tval_readback <= 0x00010000u) ? 1u : 0u;
		(void)before;
	} else {
		failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_DECREMENTER;
	}

	/* --- the frequency is the validated 19.2 MHz, or the shim's arithmetic is wrong --- */
	checks++;
	if (r->cntfrq != STAGE90_XNU_MSM8974_SHIM_EXPECTED_CNTFRQ) {
		failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_CNTFRQ;
	}

	/* --- CNTP must be masked/disabled on exit: the shim must not arm a timer it will not
	 *     service. The payload's own timer code owns the arming from here. --- */
	checks++;
	if ((shim_read_cntp_ctl() & 0x1u) != 0u && r->decrementer_roundtrip == 0u) {
		failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_TIMER_LEFT_ARMED;
	}

	r->checks = checks;
	r->failures = failures;
	r->status = (failures == 0u) ? STAGE90_STATUS_OK : STAGE90_STATUS_FAIL(failures);
	r->checksum = shim_checksum(r);

	stage90_xnu_msm8974_shim_log(r);

	if (failures != 0u) {
		xnu_log_puts("stage90 xnu_msm8974_shim: not satisfied\n");
		return -1;
	}
	xnu_log_puts("stage90 xnu_msm8974_shim: registration and hardware facts verified\n");
	return 0;
}

/*
 * The bounded run of the ordered arm path, and the first caller prepare/commit/disarm have ever
 * had. Every earlier check of this shim is a fact read once; this one drives the timer through
 * the same registered tbd_ops XNU would call, waits for the interrupt to actually arrive through
 * the payload's own handler, and turns it off again.
 *
 * Why it lives here rather than in run(): it needs IRQ delivery to be live, and run() is called
 * before the payload's own GIC and timer selftests have run. Being second is the point - by the
 * time this executes, "an interrupt can be delivered at all" is an established fact, so a failure
 * here is about the shim's sequence rather than about the platform.
 *
 * The bound matters. The spin is capped, so a timer that never fires is a reported failure and not
 * a hang - and the disarm runs on every path, so the shim cannot leave an interrupt source armed
 * that the payload's own timer code did not expect to find.
 */
int stage90_xnu_msm8974_shim_arm_demo(uint32_t interval_us)
{
	struct stage90_xnu_msm8974_shim_result *r = &g_result;
	uint64_t start;
	uint32_t waited = 0u;

	if (g_registered == 0u) {
		xnu_log_puts("stage90 xnu_msm8974_shim: arm_demo called before registration\n");
		return -1;
	}

	r->arm_interval_us = interval_us;
	r->arm_irq_before = stage90_timer_irq_count;

	if (!stage90_xnu_msm8974_shim_prepare(interval_us)) {
		return -1;
	}
	if (!stage90_xnu_msm8974_shim_commit()) {
		stage90_xnu_msm8974_shim_disarm();
		return -1;
	}

	/*
	 * Wait for the timer interrupt. The cap is derived from the requested interval rather
	 * than fixed, so a longer interval is given proportionally longer - 100x the interval,
	 * which is far more than the one tick that is actually needed and still bounded.
	 */
	start = timebase_ticks();
	while (waited < (interval_us * 100u)) {
		if (stage90_timer_irq_count != r->arm_irq_before) {
			r->arm_delivered = 1u;
			break;
		}
		waited = timebase_elapsed_us(start, timebase_ticks());
	}

	r->arm_elapsed_us = waited;
	stage90_xnu_msm8974_shim_disarm();
	r->arm_disarmed = 1u;
	r->arm_irq_after = stage90_timer_irq_count;
	r->arm_cntp_ctl = shim_read_cntp_ctl();

	xnu_log_puts("stage90 xnu_msm8974_shim arm_demo result:\n");
	xnu_log_kv32("msm8974_shim_arm_interval_us", r->arm_interval_us);
	xnu_log_kv32("msm8974_shim_arm_ticks", r->arm_ticks);
	xnu_log_kv32("msm8974_shim_arm_gicc_ctlr", r->arm_gicc_ctlr);
	xnu_log_kv32("msm8974_shim_arm_cntp_ctl", r->arm_cntp_ctl);
	xnu_log_kv32("msm8974_shim_arm_irq_before", r->arm_irq_before);
	xnu_log_kv32("msm8974_shim_arm_irq_after", r->arm_irq_after);
	xnu_log_kv32("msm8974_shim_arm_delivered", r->arm_delivered);
	xnu_log_kv32("msm8974_shim_arm_disarmed", r->arm_disarmed);
	xnu_log_kv32("msm8974_shim_arm_elapsed_us", r->arm_elapsed_us);

	if (r->arm_delivered != 1u) {
		xnu_log_puts("stage90 xnu_msm8974_shim: the timer did not fire through the arm path\n");
		return -1;
	}
	xnu_log_puts("stage90 xnu_msm8974_shim: timer armed through tbd_ops, fired, serviced, disarmed\n");
	return 0;
}

const struct stage90_xnu_msm8974_shim_result *stage90_xnu_msm8974_shim_result(void)
{
	return &g_result;
}

/*
 * --- The ordered arm path (spec section 4, final bullet) -----------------------
 *
 * XNU's timer has to be armed in a specific order, and the payload has validated it:
 * distributor first, then the timer, then IRQ delivery last (gic.c:544-554). The reason the
 * order is not arbitrary is that the last step is the one that makes the CPU *interruptible*:
 * arming the timer before the distributor means the PPI is not enabled yet when it fires,
 * and enabling delivery before either means an interrupt can arrive with nothing ready to
 * service it. Both produce a timer that either never fires or fires into a handler whose
 * state is not set up - failures that look like a broken GIC rather than a broken order.
 *
 * This is the XNU-shaped version of that sequence: it uses the registered `tbd_ops` for the
 * timer half (so the same callbacks XNU would call are the ones exercised), and it returns
 * the EOI pairing the caller needs to hand to `ml_init_timebase`.
 *
 * It deliberately does NOT arm anything by itself - see the "left armed" check in run(). A
 * bring-up helper that arms a timer the caller is not yet ready to service is how you get a
 * spurious interrupt during the ladder, so the split is: `prepare` does everything except
 * make the CPU interruptible, and `commit` is the last step and is the caller's decision.
 */
int stage90_xnu_msm8974_shim_prepare(uint32_t interval_us)
{
	struct stage90_xnu_msm8974_shim_result *r = &g_result;
	volatile uint32_t *gicd_isenabler0;
	uint32_t ticks;

	if (g_registered == 0u) {
		xnu_log_puts("stage90 xnu_msm8974_shim: prepare called before registration\n");
		r->failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_REGISTRATION;
		return 0;
	}

	/*
	 * Guard the conversion. ticks = usec * 19200000 / 1000000 = usec * 96 / 5, and the thing
	 * that must not overflow is the *intermediate* `interval_us * 96`, not `interval_us`.
	 *
	 * This read `interval_us > 0xffffffff / 19200000` until the first hardware run of the arm
	 * path, which is a bound of 223 microseconds - off by a factor of a million, and it rejected
	 * every realistic interval including the 10 ms the demo asks for. The division was there to
	 * express "the product must fit" and it expressed "the product's *quotient* must be less than
	 * the frequency", which is not a constraint at all. Found by running it, not by reading it.
	 */
	if (interval_us > (0xffffffffu / 96u)) {
		xnu_log_puts("stage90 xnu_msm8974_shim: interval too large to encode\n");
		r->failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_DECREMENTER;
		return 0;
	}
	/* usec * 96 / 5 == usec * 19.2, without a 64-bit divide helper. */
	ticks = (interval_us * 96u) / 5u;

	/* 1. Distributor: enable the timer PPI bank. A 32-bit write to the banked
	 *    ISENABLER0 covers PPIs 0-31, which is where the generic timer's 18 and 19 live. */
	gicd_isenabler0 = (volatile uint32_t *)(uintptr_t)(MSM8974_GIC_DIST_BASE + 0x100u);
	*gicd_isenabler0 = (1u << MSM8974_TIMER_CNTP_INTID);
	shim_barrier();

	/* 2. Timer: arm via the registered callback, i.e. the path XNU would call. */
	if (g_registered_ops.tbd_set_decrementer == 0) {
		r->failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_DECREMENTER;
		return 0;
	}
	g_registered_ops.tbd_set_decrementer(ticks);
	shim_barrier();

	/*
	 * 3. Enable CNTP. Deliberately NOT done here - this is the step that makes the timer
	 *    able to fire, and it belongs to `commit` together with IRQ delivery so that the
	 *    two always happen together and in that order. Doing it here would create a window
	 *    where the timer can fire while the CPU is still not interruptible, which is
	 *    harmless, and a window where it fires *after* delivery is enabled but before the
	 *    caller's state is ready, which is not.
	 */
	r->arm_ticks = ticks;
	r->arm_isenabler0 = *gicd_isenabler0;
	r->arm_prepared = 1u;
	xnu_log_kv32("msm8974_shim_arm_ticks", ticks);
	xnu_log_kv32("msm8974_shim_gicd_isenabler0", r->arm_isenabler0);
	return 1;
}

/*
 * The last step: unmask the timer, then open IRQ delivery. Order within this function
 * matters for the reason given above - CNTP_CTL before CPSR.I, never the reverse.
 */
int stage90_xnu_msm8974_shim_commit(void)
{
	struct stage90_xnu_msm8974_shim_result *r = &g_result;
	volatile uint32_t *gicc_ctlr =
		(volatile uint32_t *)(uintptr_t)(MSM8974_GIC_CPU_BASE + 0x000u);

	if (r->arm_prepared != 1u) {
		xnu_log_puts("stage90 xnu_msm8974_shim: commit called without prepare\n");
		r->failures |= STAGE90_XNU_MSM8974_SHIM_FAIL_ARM_ORDER;
		return 0;
	}

	/* The CPU interface must be enabled before delivery means anything. aboot normally
	 * leaves it on (the payload's SGI/timer selftests assert it), so this only repairs the
	 * disabled case - and it is checked rather than assumed, because "the distributor is
	 * enabled" and "this CPU will receive anything" are different statements. */
	if ((*gicc_ctlr & 1u) == 0u) {
		*gicc_ctlr = *gicc_ctlr | 1u;
		shim_barrier();
	}
	r->arm_gicc_ctlr = *gicc_ctlr;

	/* Unmask the timer, then let interrupts in. */
	shim_write_cntp_tval(r->arm_ticks);
	__asm__ volatile ("mcr p15, 0, %0, c14, c2, 1" :: "r"(1u) : "memory");
	shim_barrier();
	r->arm_cntp_ctl = shim_read_cntp_ctl();

	__asm__ volatile ("cpsie i\n\tisb" ::: "memory");
	r->arm_committed = 1u;

	xnu_log_kv32("msm8974_shim_arm_gicc_ctlr", r->arm_gicc_ctlr);
	xnu_log_kv32("msm8974_shim_arm_cntp_ctl", r->arm_cntp_ctl);
	return 1;
}

/* Disarm, in the reverse order: close delivery first, then stop the timer. */
void stage90_xnu_msm8974_shim_disarm(void)
{
	__asm__ volatile ("cpsid i\n\tisb" ::: "memory");
	shim_write_cntp_tval(0u);
	__asm__ volatile ("mcr p15, 0, %0, c14, c2, 1" :: "r"(0u) : "memory");
	shim_barrier();
}

/* Accessors the rest of the shim layer would use, exposed for the same reason. */
uint32_t stage90_xnu_msm8974_shim_registered(void)
{
	return g_registered;
}

uint32_t stage90_xnu_msm8974_shim_int_address(void)
{
	return g_registered_int_address;
}

uint32_t stage90_xnu_msm8974_shim_int_value(void)
{
	return g_registered_int_value;
}
